Repository selsa-inube/app-personas, pull requests merged in 2023-11, with the labels that each got.

#349 Cr/365/adjust edit button of personal references form
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/styles.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/types.ts
  src/pages/general/UpdateData/interface.tsx
Labels: minor

#348 sl/417/disbursement-step-saving-changes
  src/mocks/domains/domainService.mocks.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/utils/forms.ts
  src/utils/forms.tsx
  src/validations/validationRules.ts
Labels: patch

#339 jg/396/There-are-required-fields-that-do-not-say-they-are-required
  src/pages/general/UpdateData/forms/ContactDataForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Labels: patch

#351 sl/402/fix-initial-data-financial-operations
  src/mocks/users/users.mocks.tsx
Labels: patch

#329 jg/390/Redesign-SavingsCommitmentCard-according-to-new-mockups
  src/components/cards/SavingsCommitmentCard/SavingsCommitmentCard.stories.tsx
  src/components/cards/SavingsCommitmentCard/index.tsx
  src/components/cards/SavingsCommitmentCard/props.ts
  src/components/cards/SavingsCommitmentCard/styles.ts
  src/mocks/products/investments/investmentsCommitments.mocks.tsx
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/home/styles.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: enhancement

#353 Cr/398/adjust na n displayed in the asset table
  src/design/data/Table/interface.tsx
Labels: patch

#343 Cr/397/adjust empty non required field is not valid
  src/design/input/TextField/interface.tsx
  src/mocks/users/users.mocks.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Labels: patch

#356 sl/413/mock-expenses-step
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/ExpensesForm/index.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#355 sl/412/mock-income-step
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/IncomesForm/index.tsx
  src/pages/general/UpdateData/forms/IncomesForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/types.ts
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/types.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#360 sl/428/renaming-mquery-constants
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/Product/index.tsx
  src/components/modals/AttributesModal/index.tsx
  src/components/modals/DecisionModal/index.tsx
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/DebtModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/components/modals/investment/InvestmentMovementModal/index.tsx
  src/components/modals/investment/ReimbursementModal/index.tsx
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
  src/components/modals/saving/SavingMovementModal/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Title/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/InteractiveModal/index.tsx
  src/design/feedback/SectionMessage/index.tsx
  src/design/input/Fieldset/index.tsx
  src/design/layout/Blanket/index.tsx
  src/design/layout/Blanket/styles.ts
  src/design/layout/Page/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/savings/MySavings/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/request/credits/CreditRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
Labels: enhancement

#359 jg/411/Mock-Actividad-economica-step
  src/components/modals/forms/update-data/EconomicActivityModal/index.tsx
  src/components/modals/forms/update-data/EconomicActivityModal/styles.ts
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/mocks/domains/companies.ts
  src/mocks/domains/dependence.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/domains/economicSector.ts
  src/mocks/domains/position.ts
  src/mocks/domains/profession.ts
  src/mocks/users/economicActivities.mocks.ts
  src/model/domains/economicActivity/companyformalitydm.ts
  src/model/domains/economicActivity/contracttypedm.ts
  src/model/domains/economicActivity/economicactivitydm.ts
  src/model/domains/economicActivity/severanceregimedm.ts
  src/model/domains/economicActivity/workdaydm.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/EconomicActivityForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationRules.ts
Labels: minor

#365 jg/414/Mock-Relacion-con-directivos-step
  src/components/modals/forms/update-data/RelationshipWithDirectorsModal/index.tsx
  src/components/modals/forms/update-data/RelationshipWithDirectorsModal/styles.ts
  src/mocks/directors/directors.mocks.ts
  src/model/domains/personalResidence/relationshipdm.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/index.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#367 sl/423/install-auth-library
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
  src/design/navigation/Nav/index.tsx
  src/main.tsx
Labels: major

#369 sl/449/revert-to-auth0
  package-lock.json
  package.json
  src/App.tsx
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
  src/design/navigation/Nav/index.tsx
  src/main.tsx
Labels: minor

#373 sl/450/fix-horizontal-gap-personal-info
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#383 jg/452/Adjust-the-values-that-padding-receives-in-mobile
  src/design/layout/Page/styles.ts
Labels: patch

#384 jg/454/Adjust-tablet-size-responsive-Personal-Information
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#388 sl/458/check-dimensions-fieldset
  src/design/input/Fieldset/styles.ts
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Labels: patch

#390 sl/455/fix-gap-update-data-assisted
  src/pages/general/UpdateData/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
Labels: patch
