Repository selsa-inube/app-personas, pull requests merged in 2023-09, with the labels that each got.

#141 sl/183/redirect-to-savings-account
  src/App.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
Labels: minor

#142 feat: google-site-verification file
  public/googlede14b390ea01c2fb.html
Labels: bug

#143 sl/185/to-my-savings-from-accounts
  src/App.tsx
Labels: minor

#145 fix(box): adjust component visibility
  src/components/cards/Box/index.tsx
  src/pages/admin/credits/Credit/config/credit.tsx
  src/pages/admin/credits/Credit/interface.tsx
Labels: patch

#152 refactor(savingsMock): adjust elements of the aportes sociales mock
  src/mocks/products/savings/savings.mocks.tsx
Labels: minor

#153 jg/200/mock-ahorro-permanente-product
  src/mocks/products/savings/savings.mocks.tsx
Labels: minor

#154 refactor(investmentsMock): adjust objects corresponding to ahorros pr…
  src/mocks/products/investments/investments.mocks.tsx
Labels: minor

#155 sl/198/aportes-sociales-savings-account
  src/components/cards/QuickAccess/types.ts
  src/mocks/products/savings/savings.mocks.tsx
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/MySavings/config/boxes.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/types/pages/product.types.ts
  src/utils/formats.ts
Labels: minor

#156 sl/209/render-ahorros-programados
  src/App.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/styles.ts
  src/mocks/products/credits/credits.mocks.tsx
  src/mocks/products/investments/investments.mocks.tsx
  src/mocks/products/savings/savings.mocks.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/config/table.ts
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/Investment/config/investment.tsx
  src/pages/admin/investments/Investment/config/product.tsx
  src/pages/admin/investments/Investment/index.tsx
  src/pages/admin/investments/Investment/interface.tsx
  src/pages/admin/investments/Investment/types.ts
  src/pages/admin/investments/InvestmentMovements/config/table.tsx
  src/pages/admin/investments/InvestmentMovements/index.tsx
  src/pages/admin/investments/MyInvestments/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/types/pages/product.types.ts
Labels: major

#159 jg/225/CursorHover-on-Box-icon-true
  src/components/cards/Box/index.tsx
Labels: enhancement

#158 jg/224/Changes-in-mock-of-credit-products
  src/mocks/products/credits/credits.mocks.tsx
Labels: enhancement

#162 sl/226/change-mocks-savings
  src/mocks/products/savings/savings.mocks.tsx
Labels: enhancement

#160 refactor(mocks): adjust id of cdat and delete number of beneficiaries…
  src/mocks/products/investments/investments.mocks.tsx
  src/mocks/products/savings/savings.mocks.tsx
Labels: enhancement

#157 jg/210/mock-Reimbursement-modal
  src/components/modals/investment/ReimbursementModal/index.tsx
  src/components/modals/investment/ReimbursementModal/styles.ts
  src/pages/admin/investments/Investment/interface.tsx
Labels: minor

#164 sl/218/mock-programmed-commitments
  src/mocks/products/investments/investments.mocks.tsx
Labels: minor

#172 sl/227/repeating-title-contributions
  src/mocks/products/savings/savings.mocks.tsx
Labels: patch

#173 sl/229/fix-repeat-title-credits
  src/mocks/products/credits/credits.mocks.tsx
Labels: patch

#176 sl/220/insert-commitments-investments
  src/mocks/products/investments/investmentsCommitments.mocks.tsx
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/MyInvestments/index.tsx
  src/utils/products.ts
Labels: minor

#178 feat(header): extend header to insert update data link
  src/App.tsx
  src/config/header.jsx
  src/design/layout/Page/index.tsx
  src/design/layout/Page/types.ts
  src/design/navigation/Header/Header.stories.tsx
  src/design/navigation/Header/index.tsx
  src/design/navigation/Header/props.ts
  src/design/navigation/Header/styles.ts
  src/design/navigation/Header/types.ts
Labels: minor

#182 sl/237/repository-for-domains
  src/model/domains/personalInformation/bloodtypedm.ts
  src/model/domains/personalInformation/citydm.ts
  src/model/domains/personalInformation/genderdm.ts
  src/model/domains/personalInformation/maritalstatusdm.ts
Labels: minor

#184 sl/246/remove-commitment-btn-cdats
  src/pages/admin/credits/MyCredits/config/navigation.ts
  src/pages/admin/credits/MyCredits/config/products.ts
  src/pages/admin/credits/MyCredits/config/tables.ts
  src/pages/admin/home/config/products.ts
  src/pages/admin/investments/Investment/config/box.tsx
  src/pages/admin/investments/Investment/config/product.ts
  src/pages/admin/investments/Investment/interface.tsx
  src/pages/admin/investments/MyInvestments/config/navigation.ts
  src/pages/admin/investments/MyInvestments/config/products.ts
  src/pages/admin/savings/MySavings/config/navigation.ts
  src/pages/admin/savings/MySavings/config/products.ts
  src/types/pages/product.types.ts
Labels: patch

#185 jg/247/View-button-commitments-card-onClick-include-text
  src/components/cards/SavingsCommitmentCard/index.tsx
  src/components/cards/SavingsCommitmentCard/styles.ts
Labels: patch

#187 sl/248/move-product-types
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/Product/index.tsx
  src/components/modals/AttributesModal/AttributesModal.stories.tsx
  src/components/modals/AttributesModal/index.tsx
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/components/modals/investment/InvestmentMovementModal/index.tsx
  src/components/modals/investment/ReimbursementModal/index.tsx
  src/components/modals/saving/SavingMovementModal/index.tsx
  src/mocks/products/credits/credits.mocks.tsx
  src/mocks/products/investments/investments.mocks.tsx
  src/mocks/products/investments/investmentsCommitments.mocks.tsx
  src/mocks/products/savings/savings.mocks.tsx
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/CreditAmortization/config/product.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/types.ts
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/pages/admin/credits/CreditMovements/types.ts
  src/pages/admin/credits/MyCredits/ViewMovement/index.tsx
  src/pages/admin/credits/MyCredits/ViewPayment/index.tsx
  src/pages/admin/credits/MyCredits/config/products.ts
  src/pages/admin/home/config/products.ts
  src/pages/admin/home/mocks.ts
  src/pages/admin/investments/Investment/config/product.ts
  src/pages/admin/investments/Investment/types.ts
  src/pages/admin/investments/InvestmentMovements/config/table.tsx
  src/pages/admin/investments/InvestmentMovements/types.ts
  src/pages/admin/investments/MyInvestments/ViewInvestmentMovement/index.tsx
  src/pages/admin/investments/MyInvestments/config/products.ts
  src/pages/admin/savings/MySavings/ViewSavingMovement/index.tsx
  src/pages/admin/savings/MySavings/config/products.ts
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
  src/pages/admin/savings/SavingsAccountMovements/types.ts
  src/utils/products.ts
Labels: enhancement

#183 jg/242/Add-logout-link-nav
  src/design/layout/Page/index.tsx
  src/design/navigation/Nav/index.tsx
  src/design/navigation/Nav/styles.ts
Labels: minor

#189 sl/241/configure-auth0
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/admin/investments/Investment/config/box.tsx
Labels: minor, dependencies

#188 feat(usersMock): mock personal data for user in an object
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
Labels: minor

#191 sl/253/fix-repeated-reloads
  .env
  src/App.tsx
  vite.config.ts
Labels: patch

#196 sl/277/get-subdomain-redirect
  src/main.tsx
Labels: minor

#193 jg/275/Install-pre-commit-hook-for-checking-TS
  .husky/pre-commit
Labels: dependencies

#179 Cr/222/mock page for savings commitments
  src/App.tsx
  src/components/cards/Box/index.tsx
  src/mocks/products/investments/investmentsCommitments.mocks.tsx
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsCommitments/config/commitments.tsx
  src/pages/admin/savings/SavingsCommitments/config/navigation.ts
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: minor

#195 sl/239/mock-personal-info-form
  package-lock.json
  package.json
  src/design/feedback/InteractiveModal/index.tsx
  src/design/input/DropdownMenu/index.tsx
  src/design/input/Select/Select.stories.tsx
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/Select/styles.ts
  src/design/input/TextField/TextField.stories.tsx
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/styles.ts
  src/model/domains/helper.ts
  src/model/domains/personalInformation/bloodtypedm.ts
  src/model/domains/personalInformation/citydm.ts
  src/model/domains/personalInformation/genderdm.ts
  src/model/domains/personalInformation/identificationdm.ts
  src/model/domains/personalInformation/maritalstatusdm.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/CreditMovements/types.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/Investment/index.tsx
  src/pages/admin/investments/Investment/interface.tsx
  src/pages/admin/investments/Investment/types.ts
  src/pages/admin/investments/InvestmentMovements/index.tsx
  src/pages/admin/investments/InvestmentMovements/interface.tsx
  src/pages/admin/investments/InvestmentMovements/types.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/types.ts
  src/pages/admin/update-data/forms/PersonalInformationForm/index.tsx
  src/pages/admin/update-data/forms/PersonalInformationForm/interface.tsx
  src/pages/admin/update-data/forms/PersonalInformationForm/types.ts
  src/validations/regularExpressions.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: major

#201 fix(savingsCommitments): adjust value of statutory commitment
  src/mocks/products/savings/savingsCommitments.mocks.tsx
Labels: patch

#200 Cr/293/adjust select of obligaciones estatutarias
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: patch

#202 sl/245/mock-update-data-page
  src/App.tsx
  src/mocks/users/users.mocks.tsx
  src/model/domains/personalInformation/identificationtypedm.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/config/navigation.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#212 sl/297/fix-inputs-empty-messages
  src/design/input/Select/styles.ts
  src/design/input/TextField/styles.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#213 jg/295/The-Assisted-component-is-not-centered-update-data
  src/design/feedback/Assisted/styles.ts
Labels: patch

#214 sl/298/fix-focus-select
  src/design/feedback/Assisted/styles.ts
  src/design/input/Select/styles.ts
  src/design/input/TextField/styles.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#215 sl/298/fix-focus-select
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
Labels: patch

#217 sl/300/gender-fix
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#218 Cr/299/adjust readonly input
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/Select/styles.ts
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/styles.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#220 sl/282/change-commitments-button
  src/components/modals/saving/SavingCommitmentsModal/SavingCommitmentsModal.stories.tsx
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
  src/components/modals/saving/SavingCommitmentsModal/props.ts
  src/components/modals/saving/SavingCommitmentsModal/styles.ts
  src/mocks/products/savings/savingsCommitments.mocks.tsx
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/savings/SavingsCommitments/types.ts
Labels: minor

#221 sl/301/assisted-with-transition
  src/design/feedback/Assisted/Step/index.tsx
  src/design/feedback/Assisted/Step/styles.ts
  src/design/feedback/Assisted/index.tsx
Labels: enhancement

#222 jg/304/Add-description-text-for-Assisted-steps
  src/design/feedback/Assisted/Assisted.stories.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/styles.ts
  src/design/feedback/Assisted/types.ts
  src/pages/general/UpdateData/config/assisted.ts
Labels: minor

#228 Cr/308/adjust gap between product cards in the destination box
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: patch

#231 sl/310/select-only-error-message
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/Select/styles.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: enhancement

#232 sl/307/savings-commitment-card-nav
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
Labels: patch

#229 jg/311/Change-placeholder-and-validationMessages-for-dates-fields
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/validations/validationMessages.ts
Labels: enhancement

#233 sl/289/allow-config-steps-order
  src/design/feedback/Assisted/Assisted.stories.tsx
  src/design/feedback/Assisted/Step/index.tsx
  src/design/feedback/Assisted/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/stories/Assisted.stories.tsx
  src/design/feedback/Assisted/stories/StepsFlowController.tsx
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/index.tsx
Labels: minor

#234 sl/291/activos-personales-form
  src/components/modals/forms/update-data/AddAssetModal/index.tsx
  src/components/modals/forms/update-data/AddAssetModal/styles.ts
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/styles.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationRules.ts
Labels: minor

#237 sl/312/referencias-personales-form
  src/components/modals/forms/update-data/AddReferenceModal/index.tsx
  src/components/modals/forms/update-data/AddReferenceModal/styles.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/domains/referenceType.ts
  src/model/domains/personalInformation/bloodtypedm.ts
  src/model/domains/personalInformation/citydm.ts
  src/model/domains/personalInformation/genderdm.ts
  src/model/domains/personalInformation/identificationtypedm.ts
  src/model/domains/personalInformation/maritalstatusdm.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationRules.ts
Labels: minor

#219 Cr/252/create fullscreen nav component
  .storybook/preview-head.html
  index.html
  src/config/header.jsx
  src/design/layout/Page/index.tsx
  src/design/layout/Page/types.ts
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
  src/design/navigation/FullscreenNav/FullscreenMenu/styles.ts
  src/design/navigation/FullscreenNav/FullscreenNav.stories.tsx
  src/design/navigation/FullscreenNav/MultiSections/index.tsx
  src/design/navigation/FullscreenNav/MultiSections/styles.ts
  src/design/navigation/FullscreenNav/OneSection/index.tsx
  src/design/navigation/FullscreenNav/index.tsx
  src/design/navigation/FullscreenNav/props.ts
  src/design/navigation/FullscreenNav/styles.ts
  src/design/navigation/Header/index.tsx
  src/design/navigation/Header/types.ts
Labels: minor
