Repository selsa-inube/app-personas, pull requests merged in 2023-12, with the labels that each got.

#386 jg/453/Adjust-the-verification-of-the-fields-on-Update-Data
  src/design/input/TextField/interface.tsx
  src/mocks/users/users.mocks.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
Labels: patch

#398 jg/459/Adjust-max-width-to-700px-update-data
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
Labels: patch

#399 sl/456/fix-gap-tablet-personal-info
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#400 sl/463/token-label-select-textfield
  src/design/input/Select/interface.tsx
  src/design/input/TextField/interface.tsx
Labels: patch

#402 sl/464/fix-columns-sizes-table
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/styles.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/table.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/config/table.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/table.ts
Labels: patch

#372 feat(familyGroup): create familyGroup step and family member view
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/styles.ts
  src/design/input/Fieldset/index.tsx
  src/design/input/Fieldset/props.ts
  src/mocks/domains/economicSector.ts
  src/mocks/users/users.mocks.tsx
  src/model/domains/personalResidence/relationshipdm.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/mapper.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/table.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/interface.tsx
Labels: minor

#397 jg/460/Adjust-behavior-and-autocomplete-of-contactDataForm-fields
  src/design/input/TextField/interface.tsx
  src/mocks/users/users.mocks.tsx
  src/model/domains/financialOperations/countrydm.ts
  src/model/domains/personalInformation/citydm.ts
  src/model/domains/personalInformation/departamentdm.ts
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/validations/validationRules.ts
Labels: patch

#403 fix(bankTransferForm): adjust the behavior of the gap
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
Labels: patch

#405 fix(decisionModal): adjust component styles
  src/components/modals/DecisionModal/index.tsx
  src/components/modals/DecisionModal/styles.ts
Labels: patch

#401 jg/462/Adjust-the-design-of-the-Modals
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/AssetModal/styles.ts
  src/components/modals/forms/update-data/DebtModal/index.tsx
  src/components/modals/forms/update-data/DebtModal/styles.ts
  src/components/modals/forms/update-data/EconomicActivityModal/index.tsx
  src/components/modals/forms/update-data/EconomicActivityModal/styles.ts
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/styles.ts
  src/components/modals/forms/update-data/RelationshipWithDirectorsModal/index.tsx
  src/components/modals/forms/update-data/RelationshipWithDirectorsModal/styles.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
Labels: patch

#407 sl/465/fix-edit-btn-modals
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/DebtModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/EditDebt/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/interface.tsx
Labels: patch

#411 sl/470/update-step-names-credit-request
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
Labels: minor

#417 sl/471/validation-max-term-credit-conditions
  src/design/input/Select/interface.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/Textarea/index.tsx
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/styles.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
Labels: minor

#418 sl/472/max-quota-valid-credit-request
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/interface.tsx
Labels: minor

#419 sl/478/fix-padding-fieldset-responsive
  src/design/input/Fieldset/index.tsx
  src/design/input/Fieldset/styles.ts
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Labels: patch

#421 sl/479/fix-sizes-stroke-assisted
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/styles.ts
Labels: patch

#424 sl/484/fix-styles-verification-boxes
  src/design/data/Accordion/index.tsx
  src/design/data/Accordion/styles.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/config/box.ts
Labels: patch

#420 sl/481/fix-data-appear-personal-residence
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
Labels: patch

#423 sl/483/fix-modal-height-economic-activity
  src/components/modals/forms/update-data/EconomicActivityModal/styles.ts
Labels: patch

#422 sl/482/fix-0-socioeconomic-information
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/index.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/validations/validationRules.ts
Labels: patch

#427 sl/488/install-configure-pwa-plugin
  package-lock.json
  package.json
  vite.config.ts
Labels: dependencies

#426 sl/480/communication-channels-step
  src/design/input/Switch/index.tsx
  src/design/input/Switch/styles.ts
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/mappers.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/styles.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
Labels: minor

#430 sl/496/migrate-auth0-for-auth-library
  package-lock.json
  package.json
  src/App.tsx
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
  src/design/navigation/Nav/index.tsx
  src/main.tsx
Labels: minor, dependencies

#431 feat(savings): add Mock page for requesting a savings product
  src/App.tsx
  src/components/cards/RequestCard/index.tsx
  src/components/cards/RequestCard/styles.ts
  src/pages/request/savings/SavingRequest/config/cards.ts
  src/pages/request/savings/SavingRequest/config/navigation.ts
  src/pages/request/savings/SavingRequest/index.tsx
  src/routes/saving.tsx
Labels: minor

#432 sl/491/home-screen-greet-user
  src/pages/admin/home/interface.tsx
Labels: minor

#425 jg/408/Mock-editing-a-relative-in-family-group-step
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/config/tabs.ts
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/styles.ts
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/design/navigation/Tab/index.tsx
  src/design/navigation/Tab/props.ts
  src/design/navigation/Tab/stories/Tab.stories.tsx
  src/design/navigation/Tab/stories/TabController.tsx
  src/design/navigation/Tab/styles.ts
  src/design/navigation/Tabs/index.tsx
  src/design/navigation/Tabs/props.ts
  src/design/navigation/Tabs/stories/Tabs.stories.tsx
  src/design/navigation/Tabs/stories/TabsController.tsx
  src/design/navigation/Tabs/styles.ts
  src/design/navigation/Tabs/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
Labels: minor

#433 feat(header): adjust the header name to match the current user
  src/design/layout/Page/index.tsx
Labels: minor

#428 jg/469/Credit-product-option-generate-recomendation
  src/design/input/RadioCard/index.tsx
  src/design/input/RadioCard/styles.ts
  src/mocks/domains/creditProductType.ts
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/config/box.ts
Labels: minor

#440 sl/506/refactor-inputs-type-number
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/types.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommunicationChannelsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/config/form.ts
  src/utils/forms.tsx
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: enhancement

#441 jg/509/Update-unibe-auth-library
  package-lock.json
  package.json
Labels: dependencies

#437 Cr/468/change credit simulation to credit destination
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/config/mappers.ts
  src/pages/request/credits/CreditDestinationRequest/config/navigation.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CommunicationChannelsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommunicationChannelsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommunicationChannelsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CommunicationChannelsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/config/termsAndConditions.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditRequest/config/cards.ts
  src/pages/request/credits/CreditSimulationRequest/config/navigation.ts
  src/routes/credit.tsx
Labels: minor

#434 feat(cdatRequest): create mock inversión step for requesting a cdat
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/config/navigation.ts
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/types.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/forms/Summary/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/pages/request/savings/SavingRequest/config/cards.ts
  src/routes/saving.tsx
  src/utils/formats.ts
Labels: minor

#439 jg/489/Generate-Manifest-for-plugin-PWA-with-assets
  manifest.ts
  public/fondecom-192x192.png
  public/fondecom-512x512.png
  public/fondecom-64x64.png
  tsconfig.node.json
  vite.config.ts
Labels: minor

#442 sl/510/rename-step-communication-channels
  package-lock.json
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/config/mappers.ts
  src/pages/request/credits/CreditDestinationRequest/forms/ContactChannelsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/ContactChannelsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/ContactChannelsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/ContactChannelsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
Labels: enhancement

#444 sl/501/name-investment
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/props.ts
  src/design/input/TextField/styles.ts
  src/design/input/Textarea/index.tsx
  src/design/input/Textarea/props.ts
  src/design/input/Textarea/stories/Textarea.stories.tsx
  src/design/input/Textarea/stories/TextareaController.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/interface.tsx
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/types.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/types/forms.types.ts
  src/utils/forms.tsx
Labels: minor

#445 sl/507/delete-user-id-mock
  src/App.tsx
  src/mocks/products/investments/investments.mocks.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: minor

#443 sl/508/contact-channels-cdat
  src/forms/ContactChannelsForm/index.tsx
  src/forms/ContactChannelsForm/interface.tsx
  src/forms/ContactChannelsForm/mappers.ts
  src/forms/ContactChannelsForm/styles.ts
  src/forms/ContactChannelsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/forms/Summary/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  tsconfig.json
  vite.config.ts
Labels: minor

#452 fix(icon): adjust functionality based on the disabled property of the…
  src/design/data/Icon/index.tsx
Labels: patch
