Repository selsa-inube/app-personas, pull requests merged in 2023-10, with the labels that each got.

#244 sl/313/operaciones-financieras-form
  src/design/input/Select/interface.tsx
  src/model/domains/general/activedm.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#236 jg/287/Mock-and-render-ContactDataForm
  src/design/input/Fieldset/Fieldset.stories.tsx
  src/design/input/Fieldset/index.tsx
  src/design/input/Fieldset/props.ts
  src/design/input/Fieldset/styles.ts
  src/design/input/TextField/styles.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: minor

#238 jg/290/Mock-and-render-BankTransfersForm
  src/mocks/domains/accountType.ts
  src/mocks/domains/bank.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationRules.ts
Labels: minor

#247 sl/328/required-be-mark-forms
  src/components/modals/forms/update-data/AddAssetModal/index.tsx
  src/components/modals/forms/update-data/AddDebtModal/index.tsx
  src/components/modals/forms/update-data/AddReferenceModal/index.tsx
  src/design/input/TextField/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#249 sl/329/fix-modal-personal-assets
  src/components/modals/forms/update-data/AddAssetModal/index.tsx
  src/components/modals/forms/update-data/AddDebtModal/index.tsx
  src/components/modals/forms/update-data/AddReferenceModal/index.tsx
  src/mocks/domains/assetType.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/types.ts
  src/pages/general/UpdateData/forms/PersonalDebtsForm/types.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/utils/formats.ts
  src/validations/regularExpressions.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: enhancement

#252 sl/320/mock-credit-request-page
  src/App.tsx
  src/components/cards/RequestCard/RequestCard.stories.tsx
  src/components/cards/RequestCard/index.tsx
  src/components/cards/RequestCard/props.ts
  src/components/cards/RequestCard/styles.ts
  src/config/nav.jsx
  src/pages/request/credits/CreditRequest/config/cards.ts
  src/pages/request/credits/CreditRequest/config/navigation.ts
  src/pages/request/credits/CreditRequest/index.tsx
  src/routes/credit.tsx
  src/routes/myCredits.tsx
  src/routes/myInvestments.tsx
  src/routes/mySavings.tsx
Labels: major

#245 jg/314/Mock-and-render-PersonalResidenceForm-update-data
  src/design/input/TextField/styles.ts
  src/mocks/users/users.mocks.tsx
  src/model/domains/personalResidence/relationshipdm.ts
  src/model/domains/personalResidence/residencetypedm.ts
  src/model/domains/personalResidence/stratumdm.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: minor

#246 Cr/316/mock and render informacion socioeconomica form
  src/model/domains/socioeconomicInformation/educationLeveldm.ts
  src/model/domains/socioeconomicInformation/vulnerablePopulationdm.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/index.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/types.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/validations/validationRules.ts
Labels: minor

#254 sl/321/simulation-request-page
  src/pages/request/credits/CreditRequest/config/cards.ts
  src/pages/request/credits/CreditRequest/config/navigation.ts
  src/pages/request/credits/CreditRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/navigation.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
  src/routes/credit.tsx
Labels: minor

#251 jg/332/Adjustments-to-modal-AddReferenceModal
  src/components/modals/forms/update-data/AddReferenceModal/index.tsx
  src/mocks/domains/referenceType.ts
Labels: enhancement

#255 sl/334/credit-request-destination-step
  src/design/input/RadioCard/RadioCard.stories.tsx
  src/design/input/RadioCard/index.tsx
  src/design/input/RadioCard/props.ts
  src/design/input/RadioCard/styles.ts
  src/mocks/domains/creditDestination.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
Labels: minor

#256 Cr/336/create switch component
  src/design/input/Switch/index.tsx
  src/design/input/Switch/props.ts
  src/design/input/Switch/stories/Switch.stories.tsx
  src/design/input/Switch/stories/Switchcontroller.tsx
  src/design/input/Switch/styles.ts
  src/design/input/Switch/types.ts
Labels: minor

#269 jg/333/Problem-when-combining-Select-with-Formik-and-Yup
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
Labels: patch

#257 jg/322/Mock-and-render-the-comentarios-step
  src/design/input/Textarea/index.tsx
  src/design/input/Textarea/props.ts
  src/design/input/Textarea/stories/Textarea.stories.tsx
  src/design/input/Textarea/stories/TextareaController.tsx
  src/design/input/Textarea/styles.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
Labels: minor

#253 Cr/306/extend textfield to support autocomplete
  src/design/input/DropdownMenu/styles.ts
  src/design/input/TextField/TextField.stories.tsx
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/props.ts
  src/design/input/TextField/styles.ts
Labels: minor

#273 sl/335/simulation-step-credit-request
  src/design/feedback/Assisted/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/props.ts
  src/design/input/Select/interface.tsx
  src/design/input/TextField/index.tsx
  src/design/layout/Divider/Divider.stories.tsx
  src/design/layout/Divider/index.tsx
  src/design/layout/Divider/props.ts
  src/design/layout/Divider/styles.ts
  src/mocks/domains/creditProductType.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/domains/peridiocity.ts
  src/mocks/products/credits/request.mocks.ts
  src/model/domains/general/peridiocity.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/styles.ts
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
  src/types/domain.types.ts
Labels: major

#274 sl/340/check-next-button-assisted
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/index.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: patch

#275 sl/342/adjust-debt-types
  src/mocks/domains/liabilityType.ts
Labels: enhancement

#277 sl/343/adjust-modal-debt
  src/components/modals/forms/update-data/AddDebtModal/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/stories/AutocompleteController.tsx
  src/design/input/TextField/stories/TextField.stories.tsx
  src/design/input/Textarea/index.tsx
  src/design/input/Textarea/stories/Textarea.stories.tsx
  src/design/input/Textarea/stories/TextareaController.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
Labels: patch

#279 sl/346/adjustments-sosioeconomic-form
  src/model/domains/general/activedm.ts
  src/model/domains/socioeconomicInformation/educationLeveldm.ts
Labels: patch

#271 jg/324/Mock-and-render-terminos-and-condiciones-step
  src/design/input/Switch/index.tsx
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/config/termsAndConditions.ts
  src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/styles.ts
  src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
Labels: minor

#280 jg/325/Mock-and-render-the-Preliquidation-step
  src/design/input/Fieldset/styles.ts
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/types.ts
Labels: minor

#281 jg/345/Adjust-step-of-financial-operations
  src/design/input/Textarea/Counter/index.tsx
  src/design/input/Textarea/index.tsx
  src/design/input/Textarea/stories/Textarea.stories.tsx
  src/design/input/Textarea/stories/TextareaController.tsx
  src/design/input/Textarea/types.ts
  src/mocks/domains/bankForeign.ts
  src/mocks/domains/currency.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/users/users.mocks.tsx
  src/model/domains/financialOperations/countrydm.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/types.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/interface.tsx
Labels: patch

#284 Sl/349/scroll y next button
  src/design/input/RadioCard/index.tsx
  src/design/input/Select/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/index.tsx
Labels: enhancement

#285 sl/344/fix-currency-values-with-nan
  src/components/modals/forms/update-data/AddDebtModal/index.tsx
Labels: patch

#286 fix(button): added tuochable behavior
  src/design/input/Button/index.tsx
  src/design/input/Button/styles.ts
Labels: patch

#287 Cr/348/adjust section in fullscreen nav
  src/design/navigation/FullscreenNav/MultiSections/index.tsx
Labels: patch

#289 jg/359/Add-Fecha-de-vencimiento-in-ahorros-programados-product-card
  src/mocks/products/investments/investments.mocks.tsx
Labels: minor

#290 jg/356/Delete-Mis-Inversiones-navlink
  src/config/nav.jsx
Labels: minor

#292 sl/367/information-personal-verification
  src/design/data/Accordion/index.tsx
  src/design/data/Accordion/stories/Accordion.stories.tsx
  src/design/data/Accordion/styles.ts
  src/model/domains/personalInformation/bloodtypedm.ts
  src/pages/general/UpdateData/forms/Verification/index.tsx
  src/pages/general/UpdateData/interface.tsx
Labels: minor

#288 jg/351/Move-all-products-from-Inversiones-box-to-Ahorros-box-Home
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/home/index.tsx
Labels: minor

#298 sl/370/personal-assets-verification
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#300 sl/375/financial-operations-verification
  src/components/cards/BoxAttribute/index.tsx
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/types.ts
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/types.ts
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/types.ts
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#301 sl/373/personal-residence-verification
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#302 sl/374/socioeconomic-info-verification
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#293 jg/354/Delete-my-investments-route
  src/App.tsx
  src/components/modals/saving/SavingCommitmentsModal/SavingCommitmentsModal.stories.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/Investment/config/box.tsx
  src/pages/admin/investments/Investment/config/investment.tsx
  src/pages/admin/investments/Investment/config/navigation.ts
  src/pages/admin/investments/Investment/config/product.ts
  src/pages/admin/investments/Investment/index.tsx
  src/pages/admin/investments/Investment/interface.tsx
  src/pages/admin/investments/Investment/types.ts
  src/pages/admin/investments/InvestmentMovements/config/navigation.ts
  src/pages/admin/investments/InvestmentMovements/config/table.tsx
  src/pages/admin/investments/InvestmentMovements/index.tsx
  src/pages/admin/investments/InvestmentMovements/interface.tsx
  src/pages/admin/investments/InvestmentMovements/styles.ts
  src/pages/admin/investments/InvestmentMovements/types.ts
  src/pages/admin/investments/MyInvestments/ViewInvestmentMovement/index.tsx
  src/pages/admin/investments/MyInvestments/config/boxes.tsx
  src/pages/admin/investments/MyInvestments/config/navigation.ts
  src/pages/admin/investments/MyInvestments/config/products.ts
  src/pages/admin/investments/MyInvestments/index.tsx
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/table.tsx
  src/routes/myInvestments.tsx
Labels: minor

#296 sl/368/contact-data-verification
  src/components/cards/BoxAttribute/index.tsx
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#294 jg/358/Turn-on-collapse-in-boxes-home
  src/components/cards/Box/Box.stories.tsx
  src/components/cards/Box/index.tsx
  src/pages/admin/credits/Credit/config/credit.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/MyCredits/config/boxes.tsx
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/savings/MySavings/config/boxes.tsx
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: minor

#309 sl/372/personal-references-verification
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/index.tsx
Labels: minor

#304 sl/371/personal-debts-verification
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#314 sl/383/single-bar-assisted
  src/design/feedback/Assisted/Step/index.tsx
  src/design/feedback/Assisted/Step/styles.ts
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/styles.ts
Labels: enhancement

#316 sl/387/step-comments-not-required
  src/pages/request/credits/CreditSimulationRequest/index.tsx
Labels: patch

#318 sl/389/submit-button-assisted
  src/design/feedback/Assisted/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
Labels: patch

#315 sl/386/adjust-maximum-quotas
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/interface.tsx
Labels: enhancement

#319 sl/384/refactor-preliquidation-step
  src/pages/request/credits/CreditSimulationRequest/config/assisted.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/PreliquidationForm/types.ts
Labels: minor

#320 sl/391/fix-savings-breadcrumbs
  src/pages/admin/savings/SavingsAccountMovements/config/navigation.ts
Labels: patch

#313 jg/382/Resolve-warning-from-formik.handleBlur-in-Select
  src/design/input/Select/interface.tsx
Labels: patch

#321 jg/355/Render-all-savings-products-in-my-savings-routes
  src/mocks/products/investments/investments.mocks.tsx
  src/mocks/products/savings/savings.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/home/config/products.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/config/navigation.ts
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: major

#325 sl/385/verification-credit-simulation
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/SimulationForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/index.tsx
  src/pages/request/credits/CreditSimulationRequest/interface.tsx
Labels: minor

#324 Cr/366/adjust delete button of personal references form
  src/components/modals/DecisionModal/DecisionModal.stories.tsx
  src/components/modals/DecisionModal/index.tsx
  src/components/modals/DecisionModal/props.ts
  src/components/modals/DecisionModal/styles.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/DeleteReference/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/DeleteReference/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/deleteReference.config.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
Labels: minor

#322 Cr/362/adjust delete button of personal assets form
  src/pages/general/UpdateData/forms/PersonalAssetsForm/DeleteAsset/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/DeleteAsset/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/deleteAsset.config.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
Labels: minor

#323 Cr/364/adjust delete button of personal debts form
  src/pages/general/UpdateData/forms/PersonalDebtsForm/DeleteDebt/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/DeleteDebt/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/config/deleteDebt.config.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/config/table.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
Labels: minor

#338 jg/330/Personal-assets-editing-should-work
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/AssetModal/styles.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/interface.tsx
Labels: patch

#344 sl/394/add-missing-valids-disbursement
  src/design/input/Textarea/index.tsx
  src/mocks/domains/disbursementType.ts
  src/mocks/domains/domainService.mocks.ts
  src/model/domains/general/statusdm.ts
  src/model/domains/personalInformation/identificationtypedm.ts
  src/pages/request/credits/CreditSimulationRequest/config/initialValues.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/config/validationSchema.ts
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/types.ts
  src/pages/request/credits/CreditSimulationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/types/forms.types.ts
  src/utils/forms.styles.ts
  src/utils/forms.ts
  src/utils/products.ts
Labels: patch

#346 sl/403/open-boxes-update-verification
  src/design/data/Accordion/index.tsx
Labels: enhancement

#345 sl/400/valid-past-date-debts
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: patch
