Repository selsa-inube/app-personas, pull requests merged in 2023-08, with the labels that each got.

#35 feat(logo-header): clicking in header logo redirects to home
  src/design/navigation/Header/Header.stories.tsx
  src/design/navigation/Header/index.tsx
  src/design/navigation/Header/styles.ts
Labels: minor

#37 sl/5/create-title-component
  src/design/data/Title/Title.stories.tsx
  src/design/data/Title/index.tsx
  src/design/data/Title/props.ts
  src/design/data/Title/styles.ts
  src/pages/home/index.jsx
Labels: minor

#38 sl/62/navigation-in-product
  src/components/cards/Product/Product.stories.tsx
  src/components/cards/Product/index.tsx
  src/components/cards/Product/props.ts
  src/components/cards/Product/styles.ts
  src/pages/home/index.jsx
Labels: minor

#42 sl/117/create-types-alias-path
  src/design/data/Icon/index.tsx
  src/design/data/Icon/props.ts
  src/design/data/Icon/styles.ts
  src/design/data/Tag/index.tsx
  src/design/data/Tag/styles.ts
  src/design/data/Text/index.tsx
  src/design/data/Text/props.ts
  src/design/data/Text/styles.ts
  src/design/feedback/Spinner/index.tsx
  src/design/feedback/Spinner/props.ts
  src/design/feedback/Spinner/styles.ts
  src/design/input/Button/index.tsx
  src/design/input/Button/props.ts
  src/design/input/Button/styles.ts
  src/design/layout/Grid/index.tsx
  src/design/layout/Grid/props.ts
  src/design/layout/Grid/styles.ts
  src/design/layout/Stack/index.tsx
  src/design/layout/Stack/styles.ts
  tsconfig.json
  vite.config.ts
Labels: minor

#47 refactor(header-logo): change the url of the fondecom logo
  src/config/header.jsx
Labels: patch

#48 sl/125/home-page-to-typescript
  src/App.tsx
  src/components/cards/Product/index.tsx
  src/pages/admin/credit/index.tsx
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/home/config/products.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/mocks.ts
  src/pages/admin/myCredits/index.tsx
  src/types/pages/product.types.ts
Labels: minor

#43 feat(theme): create the presente theme
  .storybook/preview.jsx
  src/components/cards/Box/Box.stories.tsx
  src/components/cards/Product/Product.stories.tsx
  src/components/cards/QuickAccess/QuickAccess.stories.tsx
  src/config/theme.jsx
  src/design/data/Avatar/Avatar.stories.tsx
  src/design/data/Icon/Icon.stories.tsx
  src/design/data/Tag/Tag.stories.tsx
  src/design/data/Text/Text.stories.tsx
  src/design/data/Title/Title.stories.tsx
  src/design/data/User/User.stories.tsx
  src/design/feedback/Spinner/Spinner.stories.tsx
  src/design/input/Button/Button.stories.tsx
  src/design/layout/Page/Page.stories.tsx
  src/design/navigation/Header/Header.stories.tsx
  src/design/navigation/Nav/Nav.stories.tsx
  src/design/navigation/NavLink/NavLink.stories.tsx
  src/mocks/design/themes/fondecom/color/color.ts
  src/mocks/design/themes/fondecom/color/palette.ts
  src/mocks/design/themes/fondecom/color/stroke.ts
  src/mocks/design/themes/fondecom/color/surface.ts
  src/mocks/design/themes/fondecom/color/text.ts
  src/mocks/design/themes/fondecom/index.ts
  src/mocks/design/themes/fondecom/typography/body.ts
  src/mocks/design/themes/fondecom/typography/display.ts
  src/mocks/design/themes/fondecom/typography/fonts.ts
  src/mocks/design/themes/fondecom/typography/headline.ts
  src/mocks/design/themes/fondecom/typography/label.ts
  src/mocks/design/themes/fondecom/typography/title.ts
  src/mocks/design/themes/fondecom/typography/typography.ts
  src/mocks/design/themes/index.ts
  src/mocks/design/themes/presente/color/color.ts
  src/mocks/design/themes/presente/color/palette.ts
  src/mocks/design/themes/presente/color/stroke.ts
  src/mocks/design/themes/presente/color/surface.ts
  src/mocks/design/themes/presente/color/text.ts
  src/mocks/design/themes/presente/index.ts
  src/mocks/design/themes/presente/typography/body.ts
  src/mocks/design/themes/presente/typography/display.ts
  src/mocks/design/themes/presente/typography/fonts.ts
  src/mocks/design/themes/presente/typography/headline.ts
  src/mocks/design/themes/presente/typography/label.ts
  src/mocks/design/themes/presente/typography/title.ts
  src/mocks/design/themes/presente/typography/typography.ts
Labels: major

#52 sl/14/create-cooservunal-theme
  src/mocks/design/themes/cooservunal/color/color.ts
  src/mocks/design/themes/cooservunal/color/palette.ts
  src/mocks/design/themes/cooservunal/color/stroke.ts
  src/mocks/design/themes/cooservunal/color/surface.ts
  src/mocks/design/themes/cooservunal/color/text.ts
  src/mocks/design/themes/cooservunal/index.ts
  src/mocks/design/themes/cooservunal/typography/body.ts
  src/mocks/design/themes/cooservunal/typography/display.ts
  src/mocks/design/themes/cooservunal/typography/fonts.ts
  src/mocks/design/themes/cooservunal/typography/headline.ts
  src/mocks/design/themes/cooservunal/typography/label.ts
  src/mocks/design/themes/cooservunal/typography/title.ts
  src/mocks/design/themes/cooservunal/typography/typography.ts
  src/mocks/design/themes/index.ts
Labels: major

#50 Ap/19/redirect to my credits from box
  src/components/cards/Box/index.tsx
  src/components/cards/Box/styles.ts
  src/pages/admin/home/config/boxes.tsx
Labels: minor

#53 jg/12/create-corbanca-theme
  src/mocks/design/themes/corbanca/color/color.ts
  src/mocks/design/themes/corbanca/color/palette.ts
  src/mocks/design/themes/corbanca/color/stroke.ts
  src/mocks/design/themes/corbanca/color/surface.ts
  src/mocks/design/themes/corbanca/color/text.ts
  src/mocks/design/themes/corbanca/index.ts
  src/mocks/design/themes/corbanca/typography/body.ts
  src/mocks/design/themes/corbanca/typography/display.ts
  src/mocks/design/themes/corbanca/typography/fonts.ts
  src/mocks/design/themes/corbanca/typography/headline.ts
  src/mocks/design/themes/corbanca/typography/label.ts
  src/mocks/design/themes/corbanca/typography/title.ts
  src/mocks/design/themes/corbanca/typography/typography.ts
  src/mocks/design/themes/index.ts
Labels: major

#54 sl/71/create-box-attribute-card
  src/components/cards/Box/Box.stories.tsx
  src/components/cards/Box/props.ts
  src/components/cards/BoxAttribute/BoxAttribute.stories.tsx
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/BoxAttribute/props.ts
  src/components/cards/BoxAttribute/styles.ts
  src/design/data/Tag/index.tsx
  src/design/layout/Grid/stories/Grid.stories.tsx
Labels: minor

#51 jg/09/create-Breadcrumbs-component-and-subcomponents
  src/design/navigation/BreadcrumbEllipsis/index.tsx
  src/design/navigation/BreadcrumbEllipsis/props.ts
  src/design/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.stories.tsx
  src/design/navigation/BreadcrumbEllipsis/styles.ts
  src/design/navigation/BreadcrumbLink/index.tsx
  src/design/navigation/BreadcrumbLink/props.ts
  src/design/navigation/BreadcrumbLink/stories/BreadcrumbLink.stories.tsx
  src/design/navigation/BreadcrumbLink/stories/BreadcrumbLinkController.tsx
  src/design/navigation/BreadcrumbLink/styles.ts
  src/design/navigation/BreadcrumbMenu/index.tsx
  src/design/navigation/BreadcrumbMenu/props.ts
  src/design/navigation/BreadcrumbMenu/stories/BreadcrumbMenu.stories.tsx
  src/design/navigation/BreadcrumbMenu/styles.ts
  src/design/navigation/BreadcrumbMenuLink/index.tsx
  src/design/navigation/BreadcrumbMenuLink/props.ts
  src/design/navigation/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.stories.tsx
  src/design/navigation/BreadcrumbMenuLink/styles.ts
  src/design/navigation/Breadcrumbs/index.tsx
  src/design/navigation/Breadcrumbs/props.ts
  src/design/navigation/Breadcrumbs/stories/Breadcrumbs.Desktop.stories.tsx
  src/design/navigation/Breadcrumbs/stories/Breadcrumbs.Mobile.stories.tsx
  src/design/navigation/Breadcrumbs/stories/Breadcrumbs.stories.tsx
  src/design/navigation/Breadcrumbs/styles.ts
  src/design/navigation/Breadcrumbs/types.ts
  src/types/design.types.ts
  src/types/navigation.types.ts
Labels: minor

#40 sl/7/create-my-credits-page
  src/App.tsx
  src/components/cards/Product/index.tsx
  src/design/data/Tag/index.tsx
  src/mocks/products/credits/credits.mocks.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/myCredits/config/boxes.tsx
  src/pages/admin/myCredits/config/navigation.tsx
  src/pages/admin/myCredits/config/products.tsx
  src/pages/admin/myCredits/credit/index.tsx
  src/pages/admin/myCredits/index.tsx
  src/types/pages/product.types.ts
Labels: minor

#55 sl/127/adjust-title-component
  src/design/data/Icon/index.tsx
  src/design/data/Icon/props.ts
  src/design/data/Title/Title.stories.tsx
  src/design/data/Title/index.tsx
  src/design/data/Title/props.ts
  src/design/data/Title/styles.ts
Labels: enhancement

#62 jg/128/change-icon-for-resumen-on-nav
  src/config/nav.jsx
Labels: minor

#64 sl/129/rename-my-credit-and-credit
  src/App.tsx
  src/pages/admin/MyCredits/Credit/index.tsx
  src/pages/admin/MyCredits/config/boxes.tsx
  src/pages/admin/MyCredits/config/navigation.tsx
  src/pages/admin/MyCredits/config/products.tsx
  src/pages/admin/MyCredits/index.tsx
Labels: enhancement

#63 sl/64/product-to-credit-page
  src/components/cards/Product/index.tsx
  src/components/cards/Product/props.ts
  src/components/cards/Product/styles.ts
  src/pages/admin/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
Labels: minor

#66 sl/131/change-credits-structure
  src/App.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/MyCredits/config/boxes.tsx
  src/pages/admin/credits/MyCredits/config/navigation.tsx
  src/pages/admin/credits/MyCredits/config/products.tsx
  src/pages/admin/credits/MyCredits/index.tsx
Labels: performance

#65 sl/130/my-credits-spacing-tokens
  src/components/cards/Product/index.tsx
  src/components/cards/Product/styles.ts
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
Labels: enhancement

#70 sl/133/split-design-types
  src/design/data/Icon/index.tsx
  src/design/data/Icon/props.ts
  src/design/data/Icon/styles.ts
  src/design/data/Icon/types.ts
  src/design/data/Tag/index.tsx
  src/design/data/Tag/props.ts
  src/design/data/Tag/styles.ts
  src/design/data/Tag/types.ts
  src/design/data/Text/index.tsx
  src/design/data/Text/props.ts
  src/design/data/Text/styles.ts
  src/design/data/Text/types.ts
  src/design/feedback/Spinner/index.tsx
  src/design/feedback/Spinner/props.ts
  src/design/feedback/Spinner/styles.ts
  src/design/feedback/Spinner/types.ts
  src/design/input/Button/index.tsx
  src/design/input/Button/props.ts
  src/design/input/Button/styles.ts
  src/design/input/Button/types.ts
  src/design/layout/Grid/index.tsx
  src/design/layout/Grid/props.ts
  src/design/layout/Grid/styles.ts
  src/design/layout/Grid/types.ts
  src/design/navigation/BreadcrumbEllipsis/index.tsx
  src/design/navigation/BreadcrumbEllipsis/props.ts
  src/design/navigation/BreadcrumbEllipsis/types.ts
  src/design/navigation/BreadcrumbLink/index.tsx
  src/design/navigation/BreadcrumbLink/props.ts
  src/design/navigation/BreadcrumbLink/types.ts
  src/design/navigation/BreadcrumbMenuLink/index.tsx
  src/design/navigation/BreadcrumbMenuLink/props.ts
  src/design/navigation/BreadcrumbMenuLink/types.ts
  src/design/navigation/Breadcrumbs/index.tsx
  src/design/navigation/Breadcrumbs/types.ts
  src/types/design.types.ts
  src/types/pages/product.types.ts
Labels: major

#76 sl/114/create-table-component
  .storybook/preview-head.html
  src/design/data/Table/DisplayEntry/index.tsx
  src/design/data/Table/Pagination/Pagination.stories.tsx
  src/design/data/Table/Pagination/PaginationController.tsx
  src/design/data/Table/Pagination/index.tsx
  src/design/data/Table/Pagination/styles.ts
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/props.ts
  src/design/data/Table/stories/Table.Paginations.stories.tsx
  src/design/data/Table/stories/Table.stories.tsx
  src/design/data/Table/stories/mocks.tsx
  src/design/data/Table/stories/styles.mocks.tsx
  src/design/data/Table/styles.ts
  src/design/data/Table/types.ts
  src/design/data/Title/index.tsx
  src/design/feedback/InteractiveModal/index.tsx
  src/design/feedback/InteractiveModal/props.ts
  src/design/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/design/feedback/InteractiveModal/styles.ts
  src/design/feedback/InteractiveModal/types.ts
  src/design/input/TextField/index.tsx
  src/design/input/TextField/types.ts
  src/design/layout/Blanket/index.tsx
  src/design/layout/Blanket/stories/Blanket.stories.tsx
  src/design/layout/Blanket/stories/styles.ts
  src/design/layout/Blanket/styles.ts
Labels: minor

#78 sl/141/adjust-select-component
  src/design/input/DropdownItem/DropdownItem.stories.tsx
  src/design/input/DropdownItem/index.tsx
  src/design/input/DropdownItem/styles.ts
  src/design/input/DropdownMenu/DropdowMenu.stories.tsx
  src/design/input/DropdownMenu/index.tsx
  src/design/input/Label/Label.stories.tsx
  src/design/input/Select/Select.stories.tsx
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/Select/styles.ts
  src/design/input/Select/types.ts
  src/design/input/TextField/TextField.stories.tsx
  src/design/input/TextField/index.tsx
Labels: enhancement

#79 sl/112/credit-mock-page
  src/components/cards/BoxAttribute/styles.ts
  src/design/data/Table/interface.tsx
  src/design/data/Table/styles.ts
  src/design/data/Table/types.ts
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/Select/styles.ts
  src/mocks/products/credits/credits.mocks.tsx
  src/pages/admin/credits/Credit/config/credit.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/styles.ts
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/MyCredits/AmountValue/index.tsx
  src/types/pages/product.types.ts
Labels: major

#81 sl/120/create-credit-movements-page
  src/App.tsx
  src/design/navigation/Breadcrumbs/types.ts
  src/pages/admin/credits/Credit/config/credit.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/styles.ts
  src/pages/admin/credits/CreditMovements/types.ts
  src/pages/admin/credits/MyCredits/config/tables.tsx
Labels: major

#83 sl/142/override-select-options
  src/design/input/DropdownMenu/styles.ts
  src/design/input/Select/styles.ts
Labels: patch

#87 sl/149/my-investments-in-nav
  src/config/nav.jsx
Labels: minor

#101 sl/152/adjust-in-table
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/types.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/MyCredits/config/tables.tsx
Labels: patch

#103 sl/153/fix-overflow-box-attribute
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/BoxAttribute/styles.ts
Labels: patch

#86 feat(investment): add box for investment products in home page
  src/App.tsx
  src/mocks/products/investments/investments.mocks.tsx
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/Investment/index.tsx
  src/pages/admin/investments/MyInvestments/index.tsx
  src/types/pages/product.types.ts
Labels: minor

#104 sl/167/fix-columns-table-mobile
  src/design/data/Table/interface.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
Labels: patch

#106 jg/147/mock-investment-products
  src/mocks/products/investments/investments.mocks.tsx
  src/pages/admin/home/config/products.tsx
  src/pages/admin/home/index.tsx
  src/types/pages/product.types.ts
Labels: minor

#109 sl/158/fix-title-arrow
  src/design/data/Icon/styles.ts
  src/design/data/Title/index.tsx
Labels: patch

#107 feat(myInvestments): create myInvestments page
  src/pages/admin/investments/MyInvestments/config/boxes.tsx
  src/pages/admin/investments/MyInvestments/config/navigation.tsx
  src/pages/admin/investments/MyInvestments/config/products.tsx
  src/pages/admin/investments/MyInvestments/index.tsx
Labels: minor

#110 sl/156/fix-incomplete-breadcrumbs
  src/pages/admin/credits/Credit/config/navigation.tsx
  src/pages/admin/credits/Credit/interface.tsx
Labels: patch

#121 sl/155/refactor-user-for-avatar
  src/design/data/User/index.tsx
  src/design/navigation/Header/index.tsx
Labels: minor

#116 jg/166/Change-values-on-credits-mocks
  src/mocks/products/credits/credits.mocks.tsx
Labels: minor

#124 sl/176/move-my-investments-option
  src/config/nav.jsx
Labels: patch

#125 Cr/163/improve breadcrumbs styles
  src/design/navigation/Breadcrumbs/BreadcrumbMenu/styles.ts
  src/design/navigation/Breadcrumbs/BreadcrumbMenuLink/index.tsx
  src/design/navigation/Breadcrumbs/BreadcrumbMenuLink/styles.ts
  src/design/navigation/Breadcrumbs/styles.ts
Labels: patch

#126 sl/164/free-investment-mora
  src/components/cards/Box/index.tsx
  src/components/cards/Product/index.tsx
  src/design/input/Select/interface.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/types/pages/product.types.ts
Labels: enhancement

#127 sl/177/move-investment-box
  src/pages/admin/home/index.tsx
Labels: patch

#129 sl/179/rename-cdt-for-cdat
  src/components/cards/QuickAccess/QuickAccess.stories.tsx
  src/config/quickLinks.jsx
  src/mocks/products/investments/investments.mocks.tsx
Labels: patch

#128 sl/178/maturity-date-investment
  src/mocks/products/investments/investments.mocks.tsx
  src/pages/admin/home/config/products.tsx
Labels: patch

#115 jg/138/Use-currencyFormat-on-my-credits-pages
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/mocks/products/investments/investments.mocks.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/MyCredits/AmountValue/index.tsx
  src/pages/admin/credits/MyCredits/config/products.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/config/products.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/MyInvestments/config/products.tsx
  src/pages/admin/investments/MyInvestments/index.tsx
  src/utils/formats.ts
Labels: minor

#123 sl/186/extract-attributes-in-credit
  src/App.tsx
  src/components/cards/BoxAttribute/styles.ts
  src/mocks/products/credits/credits.mocks.tsx
  src/pages/admin/credits/Credit/config/navigation.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/CreditAmortization/config/product.ts
  src/pages/admin/credits/CreditAmortization/config/table.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/types.ts
  src/pages/admin/credits/MyCredits/config/products.tsx
  src/pages/admin/home/config/products.tsx
  src/pages/admin/investments/MyInvestments/config/products.tsx
Labels: enhancement

#131 sl/193/disappear-attributes-responsive
  src/components/cards/Product/index.tsx
  src/pages/admin/home/config/products.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/investments/MyInvestments/config/products.tsx
Labels: patch

#134 sl/194/reducing-credit-table
  src/pages/admin/credits/MyCredits/config/tables.tsx
Labels: patch

#135 sl/171/extend-box-attribute-button
  src/components/cards/BoxAttribute/BoxAttribute.stories.tsx
  src/components/cards/BoxAttribute/ButtonAttribute/index.tsx
  src/components/cards/BoxAttribute/ButtonAttribute/styles.ts
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/BoxAttribute/props.ts
Labels: minor
