Repository selsa-inube/app-personas, pull requests merged in 2024-09, with the labels that each got.

#997 feat(tabs): replace tabs component from inubekit
  package-lock.json
  package.json
  src/components/modals/general/updateData/FamilyGroupModals/EditFamilyMemberModal/config/tabs.ts
  src/design/navigation/Tab/index.tsx
  src/design/navigation/Tab/props.ts
  src/design/navigation/Tab/stories/Tab.stories.tsx
  src/design/navigation/Tab/stories/TabController.tsx
  src/design/navigation/Tab/styles.ts
  src/design/navigation/Tabs/index.tsx
  src/design/navigation/Tabs/props.ts
  src/design/navigation/Tabs/stories/Tabs.stories.tsx
  src/design/navigation/Tabs/stories/TabsController.tsx
  src/design/navigation/Tabs/styles.ts
  src/design/navigation/Tabs/types.ts
  src/mocks/design/themes/fondecom/fondecom.ts
  src/pages/general/UpdateDataUnassisted/config/tabs.ts
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#996 jlara/1324/remove-success-cdat-request
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/interface.tsx
  src/shared/forms/ContactChannelsForm/interface.tsx
Labels: enhancement

#999 jlara/1326/system-validations-cdat
  src/components/cards/payments/PaymentMethodCard/index.tsx
  src/design/input/TextField/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/mappers.ts
  src/pages/request/savings/CdatRequest/forms/PaymentMethodForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/SystemValidationsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/SystemValidationsForm/types.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: minor

#1000 jlara/1329/modal-leaving-cdat
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
Labels: minor

#1001 jlara/1330/rename-verification-cdat
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/config/box.ts
  src/pages/request/savings/CdatRequest/forms/Verification/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
Labels: enhancement

#1002 jlara/1338/cupo-personal-credit-request
  src/model/domains/general/periodicityDM.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/services/analytics/saveNetworkTracking/index.ts
  src/services/analytics/savePaymentTracking/index.ts
  src/services/analytics/saveTrafficTracking/index.ts
  src/services/analytics/saveTransferTracking/index.ts
  src/services/featureFlags/getConsultingUsers/index.ts
  src/services/featureFlags/getFeatureFlags/index.ts
  src/services/iclient/credits/getAmortization/index.ts
  src/services/iclient/credits/getMovements/index.ts
  src/services/iclient/credits/getPeriodicities/mappers.ts
  src/services/iclient/credits/getProducts/mappers.ts
  src/services/iclient/credits/getRequirements/index.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/utils/forms/forms.tsx
Labels: minor

#1003 jlara/1274/use-links-endpoint-credit
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/TermsAndConditionsForm/types.ts
  src/services/iclient/links/getLink/index.ts
  src/services/iclient/links/getLink/mappers.ts
  src/services/iclient/termsConditions/getTermsConditions/index.ts
  src/services/iclient/termsConditions/getTermsConditions/mappers.ts
  src/services/iclient/termsConditions/getTermsConditions/types.ts
Labels: minor

#1005 jlara/1341/fix-credit-requests-errors
  src/design/input/Button/index.tsx
  src/model/domains/credits/requestStatusDM.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/credits/getRequirements/types.ts
Labels: patch

#1006 jlara/1340/fix-saving-movement-value-layout
  src/components/cards/RecordCard/index.tsx
Labels: patch

#993 crojas/1313/adjust-disbursementStep-from-aids
  src/model/domains/general/accountOriginTypeDM.ts
  src/model/domains/general/statusdm.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/types.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/utils.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/index.tsx
Labels: minor

#1008 jlara/1349/adjusts-in-cdats
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/forms/SystemValidationsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
Labels: patch

#1010 jlara/1355/auto-select-account-credit
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/index.tsx
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/types.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/utils.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/types.ts
  src/pages/request/savings/CdatRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/pages/request/savings/CdatRequest/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/utils.ts
  src/shared/forms/CommentsForm/mappers.ts
  src/shared/forms/DisbursementForm/config/form.ts
  src/shared/forms/DisbursementForm/index.tsx
  src/shared/forms/DisbursementForm/interface.tsx
  src/shared/forms/DisbursementForm/mappers.ts
  src/shared/forms/DisbursementForm/types.ts
  tsconfig.json
  vite.config.ts
Labels: major

#1011 jlara/1356/refresh-btn-requests
  src/pages/admin/requests/MyRequests/index.tsx
  src/pages/admin/requests/MyRequests/interface.tsx
Labels: enhancement

#1012 jlara/1354/refactor-simulation-use-tabs
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/config/tabs.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
Labels: minor

#1013 jlara/1358/remove-bunit-header
  src/config/header.tsx
Labels: patch

#1014 Crojas/1166/replace fieldset component from inubekit
  package-lock.json
  package.json
  src/components/modals/general/updateData/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/components/modals/general/updateData/FamilyGroupModals/FamilyMemberViewModal/styles.ts
  src/design/input/Fieldset/Fieldset.stories.tsx
  src/design/input/Fieldset/index.tsx
  src/design/input/Fieldset/props.ts
  src/design/input/Fieldset/styles.ts
  src/mocks/design/themes/fondecom/fondecom.ts
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/BeneficiariesForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
Labels: major

#1017 jlara/1366/disable-simulate-button
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
Labels: patch

#1020 jlara/1372/update-toggle-lib
  package-lock.json
  package.json
Labels: dependencies

#1019 jlara/1373/fix-cycle-interest-value
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
Labels: patch

#1022 jlara/1376/redesign-documents-box
  src/mocks/products/credits/requests.mocks.ts
  src/pages/admin/requests/RequestDetail/index.tsx
  src/pages/admin/requests/RequestDetail/interface.tsx
  src/services/iclient/requests/getRequests/mappers.ts
Labels: minor

#1023 jlara/1377/use-skeleton-terms-conditions
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
Labels: enhancement

#1025 jlara/1379/adjust-aid-card
  src/components/cards/AidCard/index.tsx
  src/components/cards/AidCard/styles.ts
Labels: enhancement

#1024 jlara/1378/adjust-modal-leave-aids
  src/components/modals/general/DecisionModal/index.tsx
  src/components/modals/general/DecisionModal/styles.ts
  src/pages/request/aids/AidRequest/interface.tsx
Labels: enhancement

#1026 jlara/1380/details-situation-no-required
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
Labels: enhancement

#1027 jlara/1383/fix-loading-modal-styles
  src/components/modals/general/LoadingModal/index.tsx
  src/components/modals/general/LoadingModal/styles.ts
  src/components/modals/transfers/RechargeModal/styles.ts
  src/pages/admin/transfers/TransferOptions/index.tsx
Labels: enhancement

#1028 jlara/1385/delete-btn-payment-only-value
  src/components/cards/payments/PaymentMethodCard/index.tsx
Labels: enhancement

#1029 jlara/1386/fix-responsive-disbursement-form
  src/shared/forms/DisbursementForm/interface.tsx
Labels: patch

#1030 jlara/1387/aid-card-btn-filled
  src/components/cards/AidCard/index.tsx
Labels: enhancement

#1031 jlara/1389/adjust-record-card-responsive
  src/components/cards/RecordCard/index.tsx
Labels: enhancement

#1032 jlara/1382/fix-cerrar-sesion-mobile
  src/design/data/User/index.tsx
  src/design/data/User/styles.ts
  src/design/navigation/FullscreenNav/FullscreenMenu/styles.ts
Labels: patch

#1035 jlara/1393/system-validations-programmed-saving
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ShareMaturityForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/utils.ts
  src/shared/forms/SystemValidationsForm/index.tsx
Labels: minor

#1036 jlara/1395/change-quota-modal
  package-lock.json
  package.json
  src/components/cards/InfoCard/index.tsx
  src/components/modals/saving/ChangeQuotaModal/index.tsx
  src/components/modals/saving/ChangeQuotaModal/styles.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/request/aids/AidRequest/config/assisted.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/VerificationBoxes/index.tsx
  src/shared/forms/DisbursementForm/verification.tsx
Labels: minor

#1037 jlara/1397/remove-shadow-aid-card
  src/components/cards/AidCard/styles.ts
Labels: enhancement

#1038 jlara/1398/adjusts-savings-request-responsive
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ShareMaturityForm/interface.tsx
  src/utils/forms/forms.tsx
Labels: patch

#1039 jlara/1400/adjusts-payment-request
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/cards/payments/PaymentMethodCard/index.tsx
  src/components/layout/Totalizer/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/services/iclient/payments/createPaymentRequest/types.ts
Labels: enhancement

#1040 Crojas/1178/replace assisted component from inubekit
  package-lock.json
  package.json
  src/design/feedback/Assisted/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/props.ts
  src/design/feedback/Assisted/stories/Assisted.stories.tsx
  src/design/feedback/Assisted/stories/StepsFlowController.tsx
  src/design/feedback/Assisted/styles.ts
  src/design/feedback/Assisted/types.ts
  src/mocks/design/themes/fondecom/fondecom.ts
  src/pages/admin/payments/Pay/config/assisted.ts
  src/pages/admin/payments/Pay/forms/Verification/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/interface.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/assisted.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/utils.ts
  src/pages/general/UpdateData/forms/Verification/index.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/utils.ts
  src/pages/request/aids/AidRequest/config/assisted.ts
  src/pages/request/aids/AidRequest/forms/Verification/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/utils.ts
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/forms/Verification/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/utils.ts
Labels: major

#1041 jlara/1403/change-maturity-share-modal
  src/components/modals/saving/ActionsModal/index.tsx
  src/components/modals/saving/ModifyActionModal/index.tsx
  src/components/modals/saving/ModifyActionModal/styles.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: minor

#1043 jlara/1408/join-amount-details-situation
  src/pages/request/aids/AidRequest/config/assisted.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/AmountForm/index.tsx
  src/pages/request/aids/AidRequest/forms/AmountForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/AmountForm/types.ts
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/types.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/forms/Verification/config/box.ts
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/types.ts
Labels: minor

#1044 jlara/1410/remove-duplicated-isrequired
  src/components/modals/general/updateData/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/design/input/Textarea/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/index.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
Labels: major

#1047 jlara/1414/remove-unused-deps
  package-lock.json
  package.json
  src/vite-env.d.ts
Labels: dependencies

#1045 jlara/1411/use-formikprops-instead-formikvalues
  src/components/modals/general/updateData/AssetModal/index.tsx
  src/components/modals/general/updateData/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/components/modals/general/updateData/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/components/modals/general/updateData/ReferenceModal/index.tsx
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/FamilyMemberView/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/types.ts
  src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/EditDebt/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/shared/forms/PaymentMethodForm/config/form.ts
  src/utils/forms/forms.tsx
Labels: major

#1048 jlara/1419/generalize-documents-requirements-form
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DocumentaryRequirementsForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/shared/forms/DocumentaryRequirementsForm/index.tsx
  src/shared/forms/DocumentaryRequirementsForm/interface.tsx
  src/shared/forms/DocumentaryRequirementsForm/mappers.ts
  src/shared/forms/DocumentaryRequirementsForm/types.ts
  src/shared/forms/DocumentaryRequirementsForm/verification.tsx
Labels: minor

#1050 jlara/1423/fix-save-btn-pse-pay
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
Labels: patch

#1049 jlara/1415/adjusts-aid-request-steps
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/forms/Verification/config/box.ts
  src/pages/admin/payments/Pay/forms/Verification/index.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/forms/Verification/index.tsx
  src/pages/request/aids/AidRequest/config/assisted.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/types.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/forms/Verification/config/box.ts
  src/pages/request/aids/AidRequest/forms/Verification/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Verification/config/box.ts
  src/pages/request/savings/CdatRequest/forms/Verification/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/index.tsx
Labels: minor

#1051 jlara/1424/fix-credit-card-detail
  src/pages/admin/cards/CreditQuota/index.tsx
  src/pages/admin/cards/CreditQuota/utils.ts
  src/services/iclient/cards/getCreditQuotaDetail/index.ts
Labels: patch

#1052 jlara/1425/payments-movements-minutes-message
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
Labels: minor

#1053 jlara/1427/download-cdat-certificate
  src/components/modals/saving/ActionsModal/index.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/savings/SavingsAccount/CdatCertificateDocument/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/utilRenders.tsx
  src/services/iclient/credits/simulateCreditConditions/mappers.ts
  src/utils/dates.ts
  src/utils/print.ts
Labels: minor

#1054 jlara/1428/one-fetch-credit-simulate
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/services/iclient/credits/simulateCreditConditions/mappers.ts
  src/services/iclient/credits/simulateCreditConditions/types.ts
Labels: enhancement

#1056 crojas/1431/extend-paymentStatus-to-include-rejectedLinix
  src/model/domains/payments/paymentStatusDM.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
  src/services/iclient/transfers/getTransferHistory/mappers.ts
Labels: enhancement
