Repository selsa-inube/app-personas, pull requests merged in 2024-06, with the labels that each got.

#855 jlara/1126/show-develop-user-name
  src/components/layout/PageNotFound/index.tsx
  src/config/header.tsx
  src/context/app/index.tsx
  src/design/data/User/User.stories.tsx
  src/design/data/User/index.tsx
  src/design/layout/Page/index.tsx
  src/design/navigation/Header/Header.stories.tsx
  src/design/navigation/Header/index.tsx
  src/design/navigation/Menu/MenuHeading/index.tsx
  src/pages/admin/switchUser/index.tsx
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: enhancement

#858 jlara/1115/option-recharge-saving-accounts
  src/components/cards/Box/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/savings/SavingsAccount/utils.ts
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
Labels: minor

#856 jlara/1121/add-route-recharge-options
  src/App.tsx
  src/config/nav.tsx
  src/routes/transfers.tsx
Labels: minor

#859 jlara/1116/mock-recharge-options-screen
  src/config/nav.tsx
  src/pages/admin/transfers/TransferOptions/config/navigation.ts
  src/pages/admin/transfers/TransferOptions/index.tsx
  src/routes/transfers.tsx
Labels: minor

#861 jlara/1118/interval-refresh-history
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/transfers/TransferHistory/index.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
Labels: enhancement

#862 jlara/1120/create-recharge-modal
  src/components/modals/transfers/RechargeModal/index.tsx
  src/components/modals/transfers/RechargeModal/styles.ts
  src/model/entity/transfer.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/types.ts
  src/pages/admin/transfers/TransferOptions/index.tsx
  src/pages/admin/transfers/TransferOptions/utils.ts
  src/services/analytics/saveTransferTracking/index.ts
  src/services/iclient/transfers/createTransferRequest/index.ts
  src/services/iclient/transfers/createTransferRequest/mappers.ts
Labels: major

#863 feat(cardMovement): adjust the description in cardMovement
  src/components/cards/cards/CardMovement/CardMovement.stories.tsx
  src/components/cards/cards/CardMovement/index.tsx
Labels: patch

#865 Crojas/1133/add expired value in payments card
  src/pages/admin/payments/Pay/config/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: enhancement

#866 feat(transfers): change recargar for depositar
  src/components/modals/transfers/RechargeModal/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/transfers/TransferOptions/index.tsx
Labels: minor

#867 feat(featureFlags): add feature flags for transfer option
  src/components/layout/PageNotFound/index.tsx
  src/config/header.tsx
  src/config/nav.tsx
  src/context/app/utils.ts
  src/design/layout/Page/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#870 Crojas/1143/adjust movements in cards
  src/components/cards/cards/CardMovement/index.tsx
Labels: patch

#868 jlara/1145/total-payment-currency
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
Labels: patch

#869 jlara/1146/changes-recargar-to-depositar
  src/components/modals/transfers/RechargeModal/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/transfers/TransferOptions/index.tsx
  src/services/iclient/transfers/getTransferHistory/mappers.ts
Labels: enhancement

#872 feat(index): change lang attribute to es in index
  index.html
Labels: enhancement

#873 feat(supabase): add column customerId in payments tracking
  src/pages/admin/payments/Pay/utils.ts
  src/services/analytics/savePaymentTracking/index.ts
Labels: enhancement

#875 Develop to main 17/06/2024
  index.html
  src/pages/admin/payments/Pay/utils.ts
  src/pages/admin/transfers/TransferOptions/utils.ts
  src/services/analytics/savePaymentTracking/index.ts
  src/services/analytics/saveTransferTracking/index.ts
Labels: major

#878 jlara/1160/remove-utc-format-date
  src/utils/dates.ts
Labels: enhancement

#879 Develop to main
  src/mocks/products/cards/utils.mocks.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/utils/dates.ts
Labels: major

#881 jlara/1158/fix-load-payment-history-view
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/transfers/TransferHistory/index.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
Labels: patch

#880 jlara/1159/adjust-other-value-payment
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/CustomValueModal/utils.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/types.ts
Labels: minor

#876 crojas/1141/extend-valor-vencido-attribute
  src/components/modals/general/ExpiredPaymentModal/index.tsx
  src/components/modals/general/ExpiredPaymentModal/styles.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: minor

#882 Develop to main
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/modals/general/ExpiredPaymentModal/index.tsx
  src/components/modals/general/ExpiredPaymentModal/styles.ts
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/CustomValueModal/utils.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/types.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/transfers/TransferHistory/index.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
  src/services/iclient/credits/getCredits/mappers.ts
Labels: major

#884 jlara/1197/fix-dates-movements
  src/components/cards/cards/CardMovement/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getAmortization/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/credits/getMovements/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: patch

#886 Crojas/1157/obligations dont appear when reloading
  src/pages/admin/payments/Pay/index.tsx
Labels: patch

#887 Develop to main
  src/components/cards/cards/CardMovement/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/mocks/domains/creditProductType.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getAmortization/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/credits/getMovements/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: major

#889 jlara/1198/change-mock-domains-savings
  src/mocks/products/savings/utils.mocks.ts
  src/model/domains/general/activedm.ts
  src/model/domains/general/monthlyPayDay.ts
  src/model/domains/general/peridiocity.ts
  src/model/domains/general/statusdm.ts
  src/model/domains/general/updateData/economicActivity/companyformalitydm.ts
  src/model/domains/general/updateData/economicActivity/contracttypedm.ts
  src/model/domains/general/updateData/economicActivity/economicactivitydm.ts
  src/model/domains/general/updateData/economicActivity/reimbursementTypeDM.ts
  src/model/domains/general/updateData/economicActivity/severanceregimedm.ts
  src/model/domains/general/updateData/economicActivity/workdaydm.ts
  src/model/domains/general/updateData/financialOperations/countrydm.ts
  src/model/domains/general/updateData/personalInformation/bloodtypedm.ts
  src/model/domains/general/updateData/personalInformation/citydm.ts
  src/model/domains/general/updateData/personalInformation/departamentdm.ts
  src/model/domains/general/updateData/personalInformation/genderdm.ts
  src/model/domains/general/updateData/personalInformation/identificationTypeDM.ts
  src/model/domains/general/updateData/personalInformation/maritalstatusdm.ts
  src/model/domains/general/updateData/personalResidence/relationshipDM.ts
  src/model/domains/general/updateData/personalResidence/residencetypedm.ts
  src/model/domains/general/updateData/personalResidence/stratumdm.ts
  src/model/domains/general/updateData/socioeconomicInformation/educationLeveldm.ts
  src/model/domains/general/updateData/socioeconomicInformation/vulnerablePopulationdm.ts
  src/model/domains/general/weeklyPayDay.ts
  src/model/domains/payments/paymentStatusDM.ts
  src/model/domains/savings/savingAccountTypeDM.ts
  src/model/domains/savings/savingGmfTypeDM.ts
  src/model/domains/savings/savingInterestDM.ts
  src/model/domains/savings/savingStatusDM.ts
  src/model/domains/services/aids/aidRequestTypeDM.ts
  src/model/domains/transfers/transferSourceDM.ts
  src/services/iclient/savings/getSavings/utils.ts
  src/utils/domains.ts
Labels: major

#892 jlara/1193/reload-savings-access-page
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
Labels: minor

#891 jlara/1200/change-card-mocked-domains
  src/mocks/products/cards/utils.mocks.ts
  src/model/domains/cards/cardStatusDM.ts
  src/model/domains/cards/creditQuotaTypeDM.ts.ts
  src/services/iclient/cards/getCards/mappers.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: minor

#890 jlara/1199/change-credit-mocked-domains
  src/mocks/products/credits/utils.mocks.ts
  src/model/domains/credits/creditAmortizationTypeDM.ts
  src/model/domains/credits/creditMovementTypeDM.ts
  src/model/domains/credits/creditPaymentTypeDM.ts
  src/model/domains/credits/creditPeriodicityDM.ts
  src/services/iclient/credits/getAmortization/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/credits/getMovements/mappers.ts
  src/services/iclient/credits/getMovements/utils.ts
Labels: minor

#888 Crojas/1191/change table in my savings for movement cards
  src/components/cards/RecordCard/RecordCard.stories.tsx
  src/components/cards/RecordCard/index.tsx
  src/components/cards/RecordCard/props.ts
  src/components/cards/RecordCard/styles.ts
  src/components/cards/cards/CardMovement/CardMovement.stories.tsx
  src/components/cards/cards/CardMovement/index.tsx
  src/components/cards/cards/CardMovement/styles.ts
  src/components/cards/payments/PaymentHistoryCard/PaymentHistoryCard.stories.tsx
  src/components/cards/payments/PaymentHistoryCard/index.tsx
  src/components/cards/payments/PaymentHistoryCard/props.ts
  src/components/cards/payments/PaymentHistoryCard/styles.ts
  src/components/cards/transfers/TransferHistoryCard/TransferHistoryCard.stories.tsx
  src/components/cards/transfers/TransferHistoryCard/index.tsx
  src/components/cards/transfers/TransferHistoryCard/props.ts
  src/components/cards/transfers/TransferHistoryCard/styles.ts
  src/design/data/Tag/styles.ts
  src/model/entity/product.ts
  src/pages/admin/cards/Card/config/attributeRecord.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/config/attributeRecord.ts
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/payments/PaymentHistory/config/attributeRecord.ts
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/savings/SavingsAccount/config/attributeRecord.ts
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/styles.ts
  src/pages/admin/savings/SavingsAccountMovements/config/attributeRecord.ts
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/styles.ts
  src/pages/admin/savings/SavingsCommitments/config/attributeRecord.ts
  src/pages/admin/savings/SavingsCommitments/config/table.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/savings/SavingsCommitments/styles.ts
  src/pages/admin/transfers/TransferHistory/config/attributeRecord.ts
  src/pages/admin/transfers/TransferHistory/interface.tsx
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: minor

#893 jlara/1205/change-destination-card
  src/components/cards/credits/DestinationCard/DestinationCard.stories.tsx
  src/components/cards/credits/DestinationCard/index.tsx
  src/components/cards/credits/DestinationCard/props.ts
  src/components/cards/credits/DestinationCard/styles.ts
  src/mocks/domains/creditProductType.ts
  src/mocks/domains/domainService.mocks.ts
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
Labels: minor

#894 jlara/1217/fix-tag-open-modal
  src/components/layout/Totalizer/index.tsx
Labels: patch
