Repository selsa-inube/app-personas, pull requests merged in 2024-10, with the labels that each got.

#1061 jlara/1449/get-aids-from-endpoint
  src/components/cards/AidCard/index.tsx
  src/mocks/services/aids/aidsRequest.mocks.ts
  src/model/entity/service.ts
  src/pages/request/aids/AidOptions/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/services/iclient/aids/getAids/index.ts
  src/services/iclient/aids/getAids/mappers.ts
  tsconfig.json
Labels: minor

#1062 jlara/1444/use-enum-banks-aids
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/model/domains/general/updateData/personalInformation/identificationTypeDM.ts
  src/pages/admin/pqrs/PQRSCreate/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/services/iclient/domains/getDomains/index.ts
  src/services/iclient/domains/getDomains/mappers.ts
  src/shared/forms/DisbursementForm/config/form.ts
  src/shared/forms/DisbursementForm/index.tsx
Labels: minor

#1063 jlara/1482/aid-card-remove-desc
  src/components/cards/AidCard/AidCard.stories.tsx
  src/components/cards/AidCard/index.tsx
  src/mocks/services/aids/aidsRequest.mocks.ts
  src/model/entity/service.ts
  src/pages/request/aids/AidOptions/interfaces.tsx
  src/services/iclient/aids/getAids/mappers.ts
Labels: enhancement

#1066 crojas/1486/update-inubekit-libraries
  package-lock.json
  package.json
  src/mocks/design/themes/fondecom/fondecom.ts
  src/shared/forms/TermsAndConditionsForm/interface.tsx
Labels: minor

#1070 jlara/1489/temporal-terms-aids
  src/model/entity/request.ts
  src/pages/request/aids/AidRequest/interface.tsx
  src/shared/forms/DisbursementForm/index.tsx
  src/shared/forms/TermsAndConditionsForm/index.tsx
Labels: enhancement

#1071 jlara/1490/get-validations-aids
  src/components/cards/AidCard/index.tsx
  src/components/modals/general/AttachDocumentModal/index.tsx
  src/model/domains/services/aids/aidTypeDM.ts
  src/model/entity/service.ts
  src/pages/request/aids/AidOptions/interfaces.tsx
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/BeneficiariesForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/types.ts
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/utils.ts
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/aids/AidRequest/interface.tsx
  src/pages/request/aids/AidRequest/utils.ts
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/routes/aid.tsx
  src/services/iclient/aids/getAids/mappers.ts
  src/services/iclient/aids/getCalculatedAidConditions/index.ts
  src/services/iclient/aids/getCalculatedAidConditions/mappers.ts
  src/services/iclient/aids/getCalculatedAidConditions/types.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/credits/getRequirements/types.ts
  src/services/iclient/documents/saveDocument/mappers.ts
  src/services/iclient/documents/saveDocument/types.ts
  src/shared/forms/SystemValidationsForm/index.tsx
  src/shared/forms/SystemValidationsForm/types.ts
Labels: minor

#1073 jlara/1492/fix-beneficiary-aid-assisted
  src/model/domains/services/aids/aidTypeDM.ts
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
  src/services/iclient/aids/getAids/mappers.ts
  src/services/iclient/productRequest/getRequirements/index.ts
  src/services/iclient/productRequest/getRequirements/mappers.ts
  src/services/iclient/productRequest/getRequirements/types.ts
  src/shared/forms/SystemValidationsForm/index.tsx
Labels: patch

#1069 crojas/1441/adjust-domains-for-banks-using-the-enum-service
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
Labels: minor

#1075 jlara/1452/minimum-amount-credit-request
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/services/iclient/credits/getProducts/mappers.ts
Labels: enhancement

#1076 jlara/1496/use-alias-aids
  src/services/iclient/aids/getAids/mappers.ts
Labels: patch

#1077 jlara/1500/fix-amount-aid
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
Labels: patch

#1078 jlara/1499/adjusts-aid-request
  src/components/cards/OutlineCard/index.tsx
  src/components/cards/OutlineCard/styles.ts
  src/components/cards/ValidationCard/index.tsx
  src/pages/request/aids/AidOptions/interfaces.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
Labels: minor

#1079 jlara/1504/adjusts-my-request
  src/components/cards/RecordCard/index.tsx
  src/pages/admin/requests/MyRequests/index.tsx
  src/pages/admin/requests/MyRequests/interface.tsx
  src/pages/admin/requests/RequestDetail/interface.tsx
Labels: minor

#1080 jlara/1505/refactor-my-request-card
  src/components/cards/RecordCard/index.tsx
Labels: enhancement

#1082 jlara/1445/identification-type-enum-credit
  src/context/app/index.tsx
  src/context/app/types.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
Labels: minor

#1081 jlara/1450/control-minimal-amount-credit
  src/components/cards/credits/DestinationCard/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/config/loading.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
Labels: enhancement

#1083 jlara/1509/remove-max-days-input
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
Labels: enhancement

#1084 jlara/1510/use-aid-type-request-card
  src/components/cards/RecordCard/RecordCard.stories.tsx
  src/components/cards/RecordCard/index.tsx
  src/model/domains/services/aids/aidTypeDM.ts
  src/model/entity/request.ts
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/requests/MyRequests/interface.tsx
  src/pages/admin/requests/RequestDetail/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/services/iclient/requests/getRequests/mappers.ts
Labels: minor

#1087 jlara/PER5-38/refactor-programmed-saving-card
  src/components/cards/DestinationCard/index.tsx
  src/model/entity/request.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/DestinationForm/config/loading.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/DestinationForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/DestinationForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/utils.ts
  src/services/iclient/credits/getPaymentMethods/index.ts
  src/services/iclient/credits/getPaymentMethods/mappers.ts
  src/services/iclient/savings/getProgrammedSavingProducts/mappers.ts
Labels: minor

#1088 jlara/PER5-40/get-programmed-saving-products
  src/components/cards/DestinationCard/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/DestinationForm/config/format.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/DestinationForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/services/iclient/savings/getProgrammedSavingProducts/index.ts
  src/services/iclient/savings/getProgrammedSavingProducts/mappers.ts
Labels: minor

#1089 jlara/PER5-47/get-conditions-saving-service
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/SavingConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/services/iclient/savings/getCalculatedProgramedSavingConditions/index.ts
  src/services/iclient/savings/getCalculatedProgramedSavingConditions/mappers.ts
  src/services/iclient/savings/getCalculatedProgramedSavingConditions/types.ts
  src/services/iclient/savings/getProgrammedSavingProducts/mappers.ts
Labels: minor

#1090 jlara/PER5-39/programmed-savings-validations-service
  src/model/entity/request.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/utils.ts
  src/services/iclient/productRequest/getRequirements/mappers.ts
  src/services/iclient/productRequest/getRequirements/types.ts
  src/shared/forms/SystemValidationsForm/index.tsx
  src/shared/forms/SystemValidationsForm/utils.ts
Labels: minor

#1091 jlara/PER5-41/terms-conditions-programmed-saving
  src/model/domains/savings/shareMaturityDM.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ShareMaturityForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ShareMaturityForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ShareMaturityForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/services/iclient/credits/getCredits/mappers.ts
Labels: minor

#1093 Develop to main
  package-lock.json
  package.json
  src/App.tsx
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/DownloadCard/index.tsx
  src/components/cards/DownloadCard/styles.ts
  src/components/layout/PageNotFound/index.tsx
  src/config/nav.tsx
  src/design/layout/Page/index.tsx
  src/mocks/certifications/certificationsRequest.mocks.ts
  src/mocks/design/themes/fondecom/fondecom.ts
  src/pages/request/certifications/AccountStatementDocument/index.tsx
  src/pages/request/certifications/AccountStatementDocument/styles.ts
  src/pages/request/certifications/AccountStatementDocument/utilRenders.tsx
  src/pages/request/certifications/config/navigation.ts
  src/pages/request/certifications/config/tables.ts
  src/pages/request/certifications/index.tsx
  src/pages/request/certifications/interface.tsx
  src/pages/request/certifications/types.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/utils/texts.ts
Labels: minor
