Repository selsa-inube/app-personas, pull requests merged in 2024-01, with the labels that each got.

#455 Ap/525/change title app for fodecom personas
  index.html
Labels: minor

#457 jg/524/Change-favicon-to-Fondecom-icon
  index.html
Labels: enhancement

#458 sl/528/update-auth-library-1.0.11
  package-lock.json
  package.json
Labels: dependencies

#461 sl/529/update-home-header
  src/pages/admin/home/interface.tsx
  src/utils/dates.ts
Labels: enhancement

#460 sl/514/integrate-credit-movements
  src/App.tsx
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/context/credits/index.tsx
  src/context/credits/types.ts
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/CreditMovements/utils.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/services/iclient/credits/index.ts
  src/services/iclient/credits/mappers.ts
  src/utils/arrays.ts
  src/utils/messages.tsx
Labels: minor

#468 Ap/512/integrate credit details
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/mappers.ts
  src/utils/dictionary.ts
  src/utils/texts.ts
Labels: minor

#466 sl/532/welcome-date-change-progresses
  src/pages/admin/home/interface.tsx
Labels: enhancement

#467 sl/531/enable-scroll-y-nav
  src/design/navigation/Nav/styles.ts
Labels: patch

#469 sl/513/integrate-real-amortization-credit
  package-lock.json
  package.json
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/utils.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/utils.ts
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/utils.ts
  src/pages/admin/home/index.tsx
  src/services/iclient/credits/index.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#465 sl/516/programmed-ah-goal-step
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/design/data/Table/stories/Table.Paginations.stories.tsx
  src/design/data/Table/stories/Table.stories.tsx
  src/design/data/Table/styles.ts
  src/mocks/products/savings/programmedSavingsRates.mocks.ts
  src/model/entity/product.ts
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/navigation.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/config/table.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/pages/request/savings/SavingRequest/config/cards.ts
  src/routes/saving.tsx
  src/utils/dates.ts
Labels: minor

#473 sl/535/config-unsecured-sites
  package-lock.json
  package.json
  vite.config.ts
Labels: minor

#474 sl/534/remove-message-credits
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
Labels: patch

#448 Ap/499/mock condiciones step for cdat
  src/components/modals/saving/SavingMovementModal/index.tsx
  src/design/data/Table/styles.ts
  src/mocks/products/investments/investments.mocks.ts
  src/mocks/products/investments/investmentsCommitments.mocks.ts
  src/mocks/products/investments/investmentsRates.mocks.ts
  src/model/domains/general/peridiocity.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/config/table.ts
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/types.ts
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/utils.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/utils/texts.ts
  src/validations/validationRules.ts
Labels: minor

#475 sl/519/programmed-saving-contact-channels
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
Labels: minor

#477 Ap/536/add design system and skeleton in credits
  package-lock.json
  package.json
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/vite-env.d.ts
  tsconfig.json
Labels: minor

#476 sl/537/save-credits-in-cache
  src/pages/admin/home/index.tsx
  src/services/iclient/credits/index.ts
Labels: minor

#478 sl/538/remove-session-storage-logout
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
  src/design/navigation/Nav/index.tsx
Labels: minor

#479 sl/540/validate-no-content-requests
  src/services/iclient/credits/index.ts
Labels: minor

#480 sl/539/props-may-not-arrive-credits
  src/services/iclient/credits/mappers.ts
Labels: patch

#450 feat(ProgrammedSavingFixedRequest): create mock Quota step for reques…
  src/mocks/domains/domainService.mocks.ts
  src/mocks/domains/paymentMethodData.ts
  src/model/domains/general/biweeklyPayDay.ts
  src/model/domains/general/monthlyPayDay.ts
  src/model/domains/general/peridiocity.ts
  src/model/domains/general/weeklyPayDay.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/routes/saving.tsx
Labels: minor

#470 jg/495/Print-real-credit-products-of-logged-in-users-in-my-credits
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/credits/MyCredits/interface.tsx
Labels: minor

#481 feat(mappers): change next payment date to inmediato if credits is in…
  src/services/iclient/credits/mappers.ts
Labels: minor

#482 sl/518/name-plan-programmed-saving
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/PlanNameForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/PlanNameForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/PlanNameForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
Labels: minor

#485 sl/547/only-values-movements-modal
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/model/entity/product.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/services/iclient/credits/mappers.ts
Labels: minor

#487 sl/552/all-movements-in-credit-detail
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/utils.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/utils.ts
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/CreditMovements/utils.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#484 fix(creditDetails): rename cuota for altura de cuota
  src/services/iclient/credits/mappers.ts
Labels: minor

#489 sl/553/next-payment-modal-credit
  src/components/modals/credit/NextPaymentModal/index.tsx
  src/components/modals/credit/NextPaymentModal/styles.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#488 feat(mappers): add días de mora attribute to credit details
  src/pages/admin/credits/Credit/config/product.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#490 Ap/556/change product card attribute to saldo de capital
  src/pages/admin/credits/Credit/config/product.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#493 sl/564/mock-movement-description
  src/mocks/products/credits/utils.mocks.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#495 sl/569/sort-movements-table
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/components/modals/investment/InvestmentMovementModal/index.tsx
  src/components/modals/saving/SavingMovementModal/index.tsx
  src/mocks/products/credits/credits.mocks.tsx
  src/mocks/products/investments/investments.mocks.ts
  src/mocks/products/savings/savings.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/utils.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/MyCredits/ViewMovement/index.tsx
  src/pages/admin/credits/MyCredits/ViewPayment/index.tsx
  src/pages/admin/savings/MySavings/ViewSavingMovement/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/config/table.ts
  src/pages/general/UpdateData/forms/PersonalDebtsForm/config/table.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/config/table.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#497 sl/573/amortization-type-credit-details
  src/mocks/products/credits/utils.mocks.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#499 Cr/572/rename descuento de nomina
  src/mocks/products/credits/utils.mocks.ts
Labels: minor

#502 sl/576/all-movements-with-10
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/utils.ts
  src/services/iclient/credits/index.ts
Labels: minor

#500 sl/575/5-recent-movements-table
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/model/entity/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/utils.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditMovements/config/table.tsx
  src/services/iclient/credits/mappers.ts
  src/utils/dates.ts
Labels: minor

#503 sl/578/filter-out-movements-value-0
  src/services/iclient/credits/mappers.ts
Labels: minor

#498 Ap/543/add interest rate in credit attributes
  src/services/iclient/credits/mappers.ts
Labels: minor

#504 jg/565/Refactor-ProductCard-in-loading-state
  src/components/cards/Product/index.tsx
  src/components/cards/Product/styles.ts
  src/pages/admin/credits/MyCredits/interface.tsx
  src/pages/admin/home/interface.tsx
Labels: minor

#510 sl/583/wrong-border-radius-textfield
  src/design/input/TextField/styles.ts
Labels: patch

#511 sl/584/remove-required-in-investment-name
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/interface.tsx
Labels: patch

#456 jg/500/Mock-Reembolso-step-requesting-CDAT
  src/mocks/domains/domainService.mocks.ts
  src/mocks/domains/refundMethod.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/types.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
Labels: minor

#512 sl/585/change-color-product-attribute
  src/components/cards/BoxAttribute/ButtonAttribute/index.tsx
Labels: minor

#515 sl/612/change-button-to-filled-credit
  src/components/cards/Box/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
Labels: minor

#517 feat(creditAmortization): add column type in amortization table to in…
  src/mocks/products/credits/credits.mocks.tsx
  src/mocks/products/credits/utils.mocks.ts
  src/model/entity/product.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/MyCredits/config/tables.ts
  src/services/iclient/credits/mappers.ts
Labels: minor

#523 fix(credits): change label especificacion pago minimo to detalle in q…
  src/components/modals/credit/CreditPaymentModal/index.tsx
Labels: enhancement

#524 jg/668/Add-type-attribute-in-quota-modal-details
  src/components/modals/credit/CreditPaymentModal/index.tsx
Labels: enhancement

#483 Ap/517/mock reimbursement step for programmed saving fixed
  src/mocks/domains/domainService.mocks.ts
  src/model/domains/economicActivity/reimbursementType.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/utils.ts
Labels: minor

#526 sl/670/show-next-payment-incoming-items
  src/components/modals/credit/NextPaymentModal/index.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/mappers.ts
Labels: patch

#527 sl/622/add-link-header-update-data
  src/App.tsx
  src/config/header.tsx
  src/design/navigation/FullscreenNav/FullscreenNav.stories.tsx
  src/design/navigation/Header/Header.stories.tsx
  src/pages/general/UpdateData/config/navigation.ts
Labels: enhancement

#528 Ap/618/change all validations in update personal
  src/design/input/TextField/interface.tsx
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/index.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/types.ts
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/index.tsx
  src/pages/general/UpdateData/forms/IncomesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/index.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/index.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
  src/utils/forms/forms.tsx
Labels: minor

#532 sl/644/change-description-commitment-modal
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
Labels: enhancement

#531 sl/643/remove-savings-withdrawal-quota
  src/pages/admin/savings/SavingsAccount/config/product.ts
Labels: enhancement

#530 sl/642/remove-pending-pay-attr
  src/pages/admin/savings/SavingsAccount/config/product.ts
Labels: enhancement

#534 fix(savingsAccount): reduce the total of movements in recent movement…
  src/pages/admin/savings/SavingsAccount/index.tsx
Labels: enhancement

#537 fix(savings): change attribute valor minimo for saldo minimo
  src/mocks/products/savings/savings.mocks.tsx
Labels: enhancement

#539 jg/651/Rename-reembolso-attrubute-on-Ah-programado
  src/components/modals/investment/ReimbursementModal/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#540 sl/649/delete-interest-rate-attr
  src/pages/admin/savings/SavingsAccount/config/product.ts
Labels: enhancement

#543 fix(savings): change interest rate in cdat to efectiva anual
  src/mocks/products/investments/investments.mocks.ts
Labels: enhancement

#491 Cr/407/mock creating member in family group
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberCreateModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberCreateModal/styles.ts
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/design/feedback/Assisted/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/design/feedback/Assisted/props.ts
  src/design/feedback/Assisted/styles.ts
  src/mocks/users/referenceUsersMocks.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/assisted.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/initialValues.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/config/fieldset.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/styles.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/utils.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/formConfig.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/table.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/types.ts
Labels: major

#546 sl/655/delete-attr-automatic-debit-savings
  src/mocks/products/investments/investments.mocks.ts
  src/mocks/products/savings/savings.mocks.tsx
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#547 Ap/671/do not truncate saving account number in details product
  src/mocks/products/savings/savings.mocks.tsx
Labels: enhancement

#541 sl/653/rename-attr-request-date-cdat
  src/mocks/products/investments/investments.mocks.ts
Labels: enhancement

#548 sl/657/attr-interest-payment-cdat
  src/mocks/products/investments/investments.mocks.ts
  src/pages/admin/savings/SavingsAccount/config/product.ts
Labels: enhancement

#535 fix(savingAccount): delete beneficiarios attribute in Savings accounts
  src/pages/admin/home/index.tsx
  src/pages/admin/home/utils.ts
  src/pages/admin/savings/MySavings/config/products.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
  src/utils/texts.ts
Labels: enhancement

#551 feat(savings): create comments step whitin programmed savings
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/CommentsForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/CommentsForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/CommentsForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/config/box.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
Labels: minor

#557 sl/678/correct-credit-movements-break-points
  src/pages/admin/credits/MyCredits/config/tables.ts
Labels: patch

#553 sl/667/add-comments-step-cdat-request
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/CommentsForm/index.tsx
  src/pages/general/UpdateData/forms/CommentsForm/interface.tsx
  src/pages/general/UpdateData/forms/CommentsForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CommentsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/savings/CdatRequest/config/assisted.ts
  src/pages/request/savings/CdatRequest/config/initialValues.ts
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/config/box.ts
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/CdatRequest/interface.tsx
  src/pages/request/savings/CdatRequest/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/config/initialValues.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/types.ts
  src/shared/forms/CommentsForm/index.tsx
  src/shared/forms/CommentsForm/interface.tsx
  src/shared/forms/CommentsForm/types.ts
Labels: minor

#529 sl/621/on-change-in-programmed-saving
  src/design/input/Select/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/TextField/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/Textarea/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/PlanNameForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/PlanNameForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/interface.tsx
  src/validations/validationRules.ts
Labels: major
