Repository selsa-inube/app-personas, pull requests merged in 2024-02, with the labels that each got.

#569 sl/681/profession-field-create-family
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
Labels: patch

#568 sl/680/delete-payroll-account-bank-transfer
  src/mocks/domains/accountType.ts
Labels: patch

#567 sl/677/fix-personal-data-no-next
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
Labels: patch

#570 sl/685/nan-in-total-next-payment
  src/services/iclient/credits/getCredits/mappers.ts
Labels: patch

#574 sl/682/fix-create-asset-not-aligned
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/DebtModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
Labels: patch

#573 fix(ectionMessage): adjust sectionMessage
  src/design/feedback/SectionMessage/styles.ts
Labels: patch

#575 fix(updateData): change all action titles in tables from borrar to el…
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/table.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
Labels: enhancement

#576 sl/684/fix-creditin-arrears-date
  src/services/iclient/credits/getCredits/mappers.ts
Labels: patch

#572 Cr/620/change validations in cdat to on change
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/utils.ts
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/InvestmentNameForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/RefundForm/interface.tsx
Labels: minor

#577 Ap/690/add fieldsets in informacion personal step
  src/mocks/users/referenceUsersMocks.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/types.ts
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
Labels: enhancement

#585 sl/709/correct-sum-total-next-payment
  src/services/iclient/credits/getCredits/mappers.ts
Labels: patch

#583 sl/695/red-text-dates-amortization-due
  src/design/data/Table/index.tsx
  src/design/data/Table/interface.tsx
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
Labels: minor

#581 sl/704/arrears-tag-amortization
  src/pages/admin/credits/CreditAmortization/index.tsx
Labels: patch

#586 Ap/686/add detalle de mora attribute
  src/components/modals/credit/ArrearsDetailModal/index.tsx
  src/components/modals/credit/ArrearsDetailModal/styles.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: minor

#587 sl/710/remove-pre-cache-pwa-plugin
  manifest.ts
Labels: patch

#588 sl/715/delete-column-number-amortization
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/mocks/products/credits/credits.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/MyCredits/config/tables.ts
  src/services/iclient/credits/getAmortization/mappers.ts
Labels: minor

#592 jg/697/Refactor-fieldsets-in-ContactDataForm-step
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Labels: enhancement

#594 feat(familyMember): adjust verFamiliar modal to the corresponding col…
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/styles.ts
Labels: enhancement

#597 feat(dependencies): update design system to v5.15.0
  package-lock.json
  package.json
Labels: dependencies

#595 sl/705/integrate-cdat-endpoint
  src/components/modals/investment/InvestmentMovementModal/index.tsx
  src/components/modals/investment/InvestmentMovementModal/styles.ts
  src/context/savings/index.tsx
  src/context/savings/types.ts
  src/mocks/products/credits/credits.mocks.tsx
  src/mocks/products/investments/investments.mocks.ts
  src/mocks/products/savings/savings.mocks.tsx
  src/model/entity/product.ts
  src/pages/admin/home/config/products.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/home/utils.ts
  src/pages/admin/savings/MySavings/config/products.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccount/utils.ts
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsAccountMovements/utils.ts
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/savings/getSavings/index.ts
  src/services/iclient/savings/getSavings/mappers.ts
  src/services/iclient/savings/getSavings/utils.ts
  src/utils/texts.ts
Labels: major

#593 fix(updateDat): add descriptions in Adicionar familiar modal assisted
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/assisted.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
Labels: enhancement

#598 jg/623/Create-page-for-update-data-unassisted-process
  src/App.tsx
  src/pages/general/UpdateDataUnassisted/config/navigation.ts
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#602 sl/728/sort-payment-plan
  manifest.ts
  src/services/iclient/credits/getAmortization/mappers.ts
Labels: patch

#603 sl/727/fix-past-due-red-date-ios
  src/pages/admin/credits/CreditAmortization/config/table.tsx
  src/utils/dates.ts
Labels: patch

#604 sl/731/disable-pre-cache-pwa
  manifest.ts
  vite.config.ts
Labels: patch

#605 sl/714/change-observations-to-textarea
  src/components/modals/forms/update-data/AssetModal/index.tsx
  src/components/modals/forms/update-data/DebtModal/index.tsx
Labels: enhancement

#606 sl/717/remove-plus-next-payment-modal
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/components/modals/credit/CreditPaymentModal/index.tsx
  src/components/modals/credit/NextPaymentModal/index.tsx
Labels: enhancement

#609 sl/725/link-permanent-savings-commitments
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
  src/model/entity/product.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/SavingsAccount/config/saving.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/savings/SavingsCommitments/utils.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getProductCommitments/index.ts
  src/services/iclient/savings/getProductCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: minor

#613 fix(familyGroup): adjust actions of familyGroup table on mobile
  src/pages/general/UpdateData/forms/FamilyGroupForm/config/table.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
Labels: enhancement

#614 sl/701/add-beneficiaries-step-update-data
  src/pages/general/UpdateData/config/assisted.ts
  src/pages/general/UpdateData/forms/BeneficiariesForm/index.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/interface.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/forms/Verification/config/box.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateData/types.ts
Labels: minor

#618 sl/719/change-fields-financial-operations
  src/mocks/users/users.mocks.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/validations/validationRules.ts
Labels: enhancement

#622 sl/730/remove-calculated-fields-expenses
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
Labels: enhancement

#616 Ap/696/create datefield component
  src/design/input/DateField/index.tsx
  src/design/input/DateField/interface.tsx
  src/design/input/DateField/props.ts
  src/design/input/DateField/stories/DateField.stories.tsx
  src/design/input/DateField/stories/DateFieldController.tsx
  src/design/input/DateField/styles.ts
  src/design/input/DateField/types.ts
Labels: minor

#620 feat(updateData): create two fieldsets in operaciones financieras step
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
Labels: enhancement

#623 Cr/706/use saving produucts endpoint for ahorros programados
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
  src/services/iclient/savings/getSavings/utils.ts
Labels: minor

#621 Ap/729/extend modal ciiu to current activity
  src/components/modals/forms/update-data/EconomicActivityModal/index.tsx
  src/components/modals/forms/update-data/EconomicActivityModal/styles.ts
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
Labels: enhancement

#626 refactor(commitments): use numberCommitmentSavings for the commitment…
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: enhancement

#625 sl/747/adjust-programmed-savings-names
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: patch

#607 Cr/699/adjust editar familiar modal
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/styles.ts
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/types.ts
Labels: enhancement

#629 Ap/749/beneficiaries attribute visibility
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#627 sl/748/name-commitment-programmed-saving
  src/model/entity/product.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: patch

#631 sl/753/fix-show-permanent-savings
  src/services/iclient/savings/getSavings/mappers.ts
Labels: patch

#632 fix(savings): if there are no commitments do not display the attribute
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#633 refactor(savings): adjust gmf attribute in view savings
  src/mocks/products/savings/utils.mocks.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#635 refactor(savings): add sign less to separate name from id
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#637 sl/763/adjust-cdat-term
  src/services/iclient/savings/getSavings/utils.ts
Labels: patch

#634 refactor(savings): refactor savings-commitment attributes box to rend…
  src/pages/admin/savings/SavingsCommitments/interface.tsx
Labels: enhancement

#636 sl/759/homologate-values-saving-status
  src/mocks/products/savings/utils.mocks.ts
Labels: enhancement

#640 sl/760/change-breadcrumbs-page-titles
  src/pages/admin/savings/SavingsAccount/config/navigation.ts
  src/pages/admin/savings/SavingsAccount/interface.tsx
Labels: enhancement

#638 fix(savingsMovements): adjust movements according to type
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/services/iclient/savings/getSavings/mappers.ts
Labels: enhancement

#641 fix(savings): remove pointer in value in savings table
  src/pages/admin/savings/SavingsAccountMovements/config/table.tsx
Labels: patch

#642 sl/624/personal-information-tab
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/interface.tsx
  src/pages/general/UpdateDataUnassisted/config/navigation.ts
  src/pages/general/UpdateDataUnassisted/config/tabs.ts
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#643 sl/769/fix-two-rows-table-actions
  src/design/data/Table/styles.ts
Labels: patch

#644 sl/627/add-beneficiaries-tab
  src/pages/general/UpdateData/forms/BeneficiariesForm/index.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/config/tabs.ts
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#645 Cr/626/family group tab
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#647 sl/771/use-commitment-number-in-relationship
  src/model/entity/product.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: enhancement

#650 fix(home): total amount saved should not be shown when there are no s…
  src/pages/admin/home/interface.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: patch

#646 sl/774/use-correct-commitment-name
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: enhancement

#652 jg/773/Use-descriptionProduct-for-programmed-savings-product-name
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#653 sl/776/add-scroll-x-commitments
  src/components/cards/Box/styles.ts
  src/components/cards/Product/index.tsx
  src/components/cards/SavingsCommitmentCard/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/home/styles.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: patch

#655 jg/778/Add-attribute-request-date-in-programmed-savings
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#656 Ap/777/fix spacing products and commitments
  src/pages/admin/home/interface.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: patch

#657 sl/780/adjust-commitments-due-date-validation
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: patch
