Repository selsa-inube/app-personas, pull requests merged in 2024-03, with the labels that each got.

#662 feat(updateData): added tab for bank transfers
  src/pages/general/UpdateData/forms/BankTransfersForm/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#663 feat(updateDataUnassisted): add content of tab Residencia Personal
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#665 sl/632/add-tab-financial-operations
  src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#664 Cr/631/add referencias personales tab
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#658 feat(updateDataUnassisted): add content of tab activos personales
  src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#659 feat(updateData): adjust addReference modal in personalReferences step
  src/components/modals/forms/update-data/ReferenceModal/index.tsx
  src/components/modals/forms/update-data/ReferenceModal/styles.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/PersonalReferencesForm/EditReference/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalReferencesForm/types.ts
Labels: enhancement

#580 jg/520/Mock-debito-atomatico-in-cuota-step-Ah-programado
  src/mocks/domains/accountDebitType.ts
  src/mocks/domains/domainService.mocks.ts
  src/model/domains/general/biweeklyPayDay.ts
  src/model/domains/general/monthlyPayDay.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/types.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/types/forms.types.ts
  src/utils/forms/forms.tsx
Labels: minor

#668 feat(savings): add Fecha vencimiento attribute in ah programado
  src/pages/admin/savings/SavingsAccount/config/product.ts
Labels: enhancement

#661 feat(updateDataUnassisted): add content of tab Deudas Personales
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#667 sl/635/add-economic-activity-tab
  src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#660 Ap/625/add contact data tab
  src/mocks/users/referenceUsersMocks.ts
  src/mocks/users/users.mocks.tsx
  src/model/entity/user.ts
  src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/initialValues.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/types.ts
  src/pages/general/UpdateDataUnassisted/interface.tsx
  src/shared/forms/ContactChannelsForm/mappers.ts
  src/shared/forms/ContactChannelsForm/types.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: minor

#672 sl/639/add-comments-tab
  src/pages/general/UpdateDataUnassisted/config/tabs.ts
  src/pages/general/UpdateDataUnassisted/interface.tsx
  src/shared/forms/CommentsForm/index.tsx
  src/shared/forms/CommentsForm/interface.tsx
Labels: minor

#670 Cr/637/add expenses tab
  src/pages/general/UpdateData/forms/ExpensesForm/index.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateDataUnassisted/interface.tsx
Labels: minor

#671 sl/796/use-correcrt-arrears-value-credit
  src/services/iclient/credits/getCredits/mappers.ts
Labels: enhancement

#617 jg/658/Dinamically-render-Interest-payments-table-in-CDAT
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/services/iclient/savings/getSavings/utils.ts
Labels: minor

#673 sl/799/create-my-cards-route
  src/App.tsx
  src/routes/myCards.tsx
Labels: minor

#675 Ap/797/change icons pwa and favicon
  manifest.ts
  public/fondecom-16x16.png
  public/fondecom-192x192.png
  public/fondecom-512x512.png
  public/fondecom-64x64.png
Labels: minor

#680 Ap/803/mock cupo credito data
  src/mocks/products/cards/creditQuotas.mock.ts
  src/model/entity/product.ts
Labels: enhancement

#681 sl/811/fix-tag-position-cards
  src/components/cards/SavingsCommitmentCard/index.tsx
Labels: patch

#682 Cr/801/create consulta de tarjetas page
  src/components/modals/cards/HandlingFeeModal/index.tsx
  src/components/modals/cards/HandlingFeeModal/styles.ts
  src/components/modals/cards/SavingAccountsModal/index.tsx
  src/components/modals/cards/SavingAccountsModal/styles.ts
  src/mocks/products/cards/cards.mock.ts
  src/pages/admin/cards/Card/config/card.tsx
  src/pages/admin/cards/Card/config/navigation.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/Card/types.ts
  src/routes/myCards.tsx
Labels: minor

#639 jg/744/Change-all-date-fields-for-datefield-component
  src/components/modals/forms/update-data/DebtModal/index.tsx
  src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
  src/design/input/DateField/index.tsx
  src/design/input/DateField/interface.tsx
  src/mocks/users/users.mocks.tsx
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/index.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/validations/validationRules.ts
Labels: major

#687 sl/818/change-attr-deadline-cdats
  src/mocks/products/investments/investments.mocks.ts
  src/pages/admin/savings/SavingsAccount/config/product.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#686 jg/804/Mock-cupo-de-credito-Box-in-consulta-de-tarjetas
  src/components/cards/Box/index.tsx
  src/components/modals/InfoModal/index.tsx
  src/components/modals/InfoModal/styles.ts
  src/mocks/products/cards/creditQuotas.mock.ts
  src/model/entity/product.ts
  src/pages/admin/cards/Card/config/card.tsx
  src/pages/admin/cards/Card/config/modals.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/Card/types.ts
  src/utils/dates.ts
Labels: minor

#689 feat(cardPage): concat type of movement in credit installment
  src/mocks/products/cards/creditQuotas.mock.ts
  src/model/entity/product.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/interface.tsx
Labels: enhancement

#692 sl/824/use-card-end-point
  src/mocks/products/cards/cards.mock.ts
  src/mocks/products/cards/utils.mocks.ts
  src/pages/admin/cards/Card/config/card.tsx
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/Card/utils.ts
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/cards/getCards/mappers.ts
  src/services/iclient/cards/getMovements/index.ts
  src/services/iclient/cards/getMovements/mappers.ts
Labels: minor

#690 Ap/807/create current consumption card
  src/components/cards/CurrentConsumption/CurrentConsumption.stories.tsx
  src/components/cards/CurrentConsumption/CurrentConsumptionBox/index.tsx
  src/components/cards/CurrentConsumption/index.tsx
  src/components/cards/CurrentConsumption/props.ts
  src/components/cards/CurrentConsumption/styles.ts
  src/components/cards/QuotaDetailBox/QuotaDetailBox.stories.tsx
  src/mocks/products/cards/consumptions.mocks.ts
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/cards/CreditQuota/index.tsx
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/pages/admin/cards/CreditQuota/types.ts
Labels: minor

#700 jg/833/integrate-details-of-valor-proximo-pago-and-pago-total-cards
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/services/iclient/cards/creditQuotas/mappers.ts
Labels: minor

#699 Cr/832/create screen for movements of card
  src/components/cards/CardMovement/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/config/navigation.ts
  src/pages/admin/cards/CardMovements/index.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/cards/CardMovements/styles.ts
  src/pages/admin/cards/CardMovements/types.ts
  src/pages/admin/cards/CardMovements/utils.ts
  src/routes/myCards.tsx
Labels: minor

#701 jg/839/Homologate-AnObligation-for-Rotative
  src/mocks/products/cards/utils.mocks.ts
Labels: enhancement

#694 jg/827/NextPaymentValue-commitment-return-NaN
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: patch

#702 sl/842/validate-next-payment-quota
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/utils.ts
  src/pages/admin/cards/CardMovements/utils.ts
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/cards/CreditQuota/utils.ts
  src/services/iclient/cards/getCreditQuotas/index.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: enhancement

#704 Ap/843/validate next payment date quota
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: enhancement

#705 jg/846/hide-payment-details-if-isNaN
  src/pages/admin/cards/CreditQuota/interface.tsx
Labels: patch

#703 Cr/840/adjust visibility of consumption table
  src/pages/admin/cards/CreditQuota/interface.tsx
Labels: enhancement

#708 sl/844/create-separate-context-cards
  src/context/cards/index.tsx
  src/context/cards/types.ts
Labels: minor

#693 jg/813/Develop-Menu-component-with-subcomponents
  src/design/navigation/Menu/Menu.stories.tsx
  src/design/navigation/Menu/MenuHeading/MenuHeading.stories.tsx
  src/design/navigation/Menu/MenuHeading/index.tsx
  src/design/navigation/Menu/MenuHeading/props.ts
  src/design/navigation/Menu/MenuItem/MenuItem.stories.tsx
  src/design/navigation/Menu/MenuItem/index.tsx
  src/design/navigation/Menu/MenuItem/props.ts
  src/design/navigation/Menu/MenuItem/styles.ts
  src/design/navigation/Menu/MenuItem/types.ts
  src/design/navigation/Menu/MenuSection/MenuSection.stories.tsx
  src/design/navigation/Menu/MenuSection/index.tsx
  src/design/navigation/Menu/MenuSection/props.ts
  src/design/navigation/Menu/MenuSection/types.ts
  src/design/navigation/Menu/MenuUser/MenuUser.stories.tsx
  src/design/navigation/Menu/MenuUser/index.tsx
  src/design/navigation/Menu/MenuUser/props.ts
  src/design/navigation/Menu/index.tsx
  src/design/navigation/Menu/props.ts
  src/design/navigation/Menu/styles.ts
Labels: minor

#710 feat(consumptionTable): refactor visibility of consumption table
  src/pages/admin/cards/CreditQuota/interface.tsx
Labels: enhancement
