Repository selsa-inube/app-personas, pull requests merged in 2024-05, with the labels that each got.

#791 sl/1004/fetch-all-history-payments
  src/pages/admin/payments/PaymentHistory/index.tsx
Labels: enhancement

#792 sl/1007/handle-error-payment-request
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/interface.tsx
  src/services/iclient/payments/createPaymentRequest/index.ts
Labels: enhancement

#795 sl/1012/adjusts-payment-request-body
  src/mocks/payments/payments.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/types.ts
  src/pages/admin/payments/Pay/utils.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
Labels: enhancement

#796 sl/972/connect-traffic-tracking
  src/config/enviroment.ts
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/model/entity/featureFlag.ts
  src/services/analytics/saveTraffic/index.ts
  src/services/config/supabase/config.ts
  src/services/featureFlags/db.sql
  src/services/featureFlags/getFeatureFlags/index.ts
  src/services/featureFlags/getFeatureFlags/mappers.ts
  src/services/featuredFlags/getFeaturedFlags/mappers.ts
Labels: minor

#797 sl/1009/connect-payments-tracking
  src/context/app/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/services/analytics/savePaymentTracking/index.ts
  src/services/analytics/saveTrafficTracking/index.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: minor

#799 sl/1016/fix-cards-consult
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/CreditQuota/index.tsx
Labels: patch

#798 Cr/1015/adjust retiro movement in cards
  src/pages/admin/cards/Card/config/product.ts
Labels: enhancement

#801 sl/1019/business-unit-production
  src/config/enviroment.ts
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/cards/getCreditQuotaDetail/index.ts
  src/services/iclient/cards/getCreditQuotas/index.ts
  src/services/iclient/cards/getMovements/index.ts
  src/services/iclient/credits/getAmortization/index.ts
  src/services/iclient/credits/getCredits/index.ts
  src/services/iclient/credits/getMovements/index.ts
  src/services/iclient/payments/createPaymentRequest/index.ts
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/savings/getCommitments/index.ts
  src/services/iclient/savings/getSavings/index.ts
Labels: enhancement

#800 sl/1011/publish-failed-payment-teams
  src/config/enviroment.ts
  src/pages/admin/payments/Pay/utils.ts
  src/services/analytics/savePaymentTracking/index.ts
  src/services/teams/sendMessage/index.ts
  src/services/teams/sendMessage/mappers.ts
Labels: minor

#803 refactor(pwa): rename app name personas to fondecom
  manifest.ts
Labels: enhancement

#804 sl/1042/fix-refresh-payments
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
  src/utils/arrays.ts
Labels: patch

#802 fix(refactor): adjust cuenta para reembolso attribute
  src/mocks/products/savings/utils.mocks.ts
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/services/iclient/savings/getSavings/utils.ts
Labels: enhancement

#805 sl/1044/send-date-payment-request
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: enhancement

#806 sl/1047/reference-movement-card
  src/components/cards/CardMovement/CardMovement.stories.tsx
  src/components/cards/CardMovement/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: enhancement

#808 jlara/1050/request-links-nav
  src/App.tsx
  src/components/layout/PageNotFound/index.tsx
  src/config/header.tsx
  src/config/nav.tsx
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/design/layout/Page/Page.stories.tsx
  src/design/layout/Page/index.tsx
  src/design/navigation/FullscreenNav/FullscreenNav.stories.tsx
  src/pages/admin/home/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditRequest/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/SavingRequest/index.tsx
Labels: minor

#809 jlara/1055/route-aid-request
  src/App.tsx
  src/routes/aid.tsx
Labels: enhancement

#810 jlara/1073/adjust-payment-states
  src/mocks/payments/utils.mocks.ts
Labels: enhancement

#811 jlara/1070/sort-movements-savings
  src/services/iclient/savings/getSavings/mappers.ts
Labels: enhancement

#814 jlara/1072/adjust-response-payment-request
  src/design/layout/Page/index.tsx
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: enhancement

#815 Develop to main
  .github/workflows /github-actions.yml
  src/App.tsx
  src/components/layout/PageNotFound/index.tsx
  src/config/header.tsx
  src/config/nav.tsx
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/design/layout/Page/Page.stories.tsx
  src/design/layout/Page/index.tsx
  src/design/navigation/FullscreenNav/FullscreenNav.stories.tsx
  src/mocks/payments/utils.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/home/interface.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditRequest/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/SavingRequest/index.tsx
  src/routes/aid.tsx
  src/services/iclient/payments/createPaymentRequest/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: minor

#817 jlara/1075/empty-payment-history
  src/components/cards/OutlineCard/index.tsx
  src/components/cards/OutlineCard/styles.ts
  src/pages/admin/payments/PaymentHistory/EmptyRecords/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: minor

#818 Crojas/1052/create aid request screen
  src/pages/request/aids/Aid/config/navigation.ts
  src/pages/request/aids/Aid/index.tsx
  src/routes/aid.tsx
Labels: enhancement

#819 jlara/1049/redirect-specific-screen
  README.md
  src/config/enviroment.ts
  src/main.tsx
  src/pages/admin/payments/Pay/utils.ts
Labels: enhancement

#820 jlara/1054/create-aid-card
  src/components/cards/AidCard/AidCard.stories.tsx
  src/components/cards/AidCard/index.tsx
  src/components/cards/AidCard/props.ts
  src/components/cards/AidCard/styles.ts
  src/components/cards/RequestCard/index.tsx
  src/components/cards/cards/CardMovement/CardMovement.stories.tsx
  src/components/cards/cards/CardMovement/index.tsx
  src/components/cards/cards/CardMovement/props.ts
  src/components/cards/cards/CardMovement/styles.ts
  src/components/cards/cards/CurrentConsumption/CurrentConsumption.stories.tsx
  src/components/cards/cards/CurrentConsumption/CurrentConsumptionBox/index.tsx
  src/components/cards/cards/CurrentConsumption/index.tsx
  src/components/cards/cards/CurrentConsumption/props.ts
  src/components/cards/cards/CurrentConsumption/styles.ts
  src/components/cards/cards/QuotaDetailBox/QuotaDetailBox.stories.tsx
  src/components/cards/cards/QuotaDetailBox/index.tsx
  src/components/cards/cards/QuotaDetailBox/props.ts
  src/components/cards/cards/QuotaDetailBox/styles.ts
  src/components/cards/payments/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/cards/payments/PaymentCard/props.ts
  src/components/cards/payments/PaymentCard/styles.ts
  src/components/cards/payments/PaymentHistoryCard/PaymentHistoryCard.stories.tsx
  src/components/cards/payments/PaymentHistoryCard/index.tsx
  src/components/cards/payments/PaymentHistoryCard/props.ts
  src/components/cards/payments/PaymentHistoryCard/styles.ts
  src/components/cards/payments/PaymentInformationCard/PaymentInformationCard.stories.tsx
  src/components/cards/payments/PaymentInformationCard/index.tsx
  src/components/cards/payments/PaymentInformationCard/props.ts
  src/components/cards/payments/PaymentInformationCard/styles.ts
  src/components/cards/payments/PaymentMethodCard/index.tsx
  src/components/cards/payments/PaymentMethodCard/styles.ts
  src/components/modals/payments/PaymentTotalModal/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
Labels: minor

#821 jlara/1059/mock-data-aid-request
  src/App.tsx
  src/mocks/services/aids/aidsRequest.mocks.ts
  src/model/entity/service.ts
Labels: minor

#823 jlara/1060/use-possible-aids-mocked
  src/App.tsx
  src/components/cards/AidCard/AidCard.stories.tsx
  src/components/cards/AidCard/index.tsx
  src/mocks/services/aids/aidsRequest.mocks.ts
  src/pages/request/aids/AidOptions/config/navigation.ts
  src/pages/request/aids/AidOptions/index.tsx
  src/pages/request/aids/AidOptions/interfaces.tsx
  src/pages/request/credits/CreditDestinationRequest/config/navigation.ts
  src/pages/request/credits/CreditRequest/index.tsx
  src/routes/aid.tsx
Labels: minor

#822 Crojas/973/connect app with network tracking
  src/context/app/index.tsx
  src/services/analytics/saveNetworkTracking/index.ts
  src/services/analytics/saveTrafficTracking/index.ts
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/cards/getCreditQuotaDetail/index.ts
  src/services/iclient/cards/getCreditQuotas/index.ts
  src/services/iclient/cards/getMovements/index.ts
  src/services/iclient/cards/getMovements/mappers.ts
  src/services/iclient/credits/getAmortization/index.ts
  src/services/iclient/credits/getCredits/index.ts
  src/services/iclient/credits/getMovements/index.ts
  src/services/iclient/payments/createPaymentRequest/index.ts
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/savings/getCommitments/index.ts
  src/services/iclient/savings/getSavings/index.ts
Labels: major

#825 jlara/1076/remove-approval-users-prod
  src/components/layout/PageNotFound/index.tsx
  src/context/app/index.tsx
  src/context/app/types.ts
  src/design/layout/Page/index.tsx
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/CardMovements/index.tsx
  src/pages/admin/cards/Consumption/index.tsx
  src/pages/admin/cards/CreditQuota/index.tsx
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/SavingsAccount/index.tsx
  src/pages/admin/savings/SavingsAccountMovements/index.tsx
  src/pages/admin/savings/SavingsCommitments/index.tsx
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/credits/getCredits/index.ts
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/savings/getCommitments/index.ts
  src/services/iclient/savings/getSavings/index.ts
Labels: major

#828 jlara/1061/aids-amount-step
  src/components/cards/payments/PaymentMethodCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/TextField/styles.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/AmountForm/index.tsx
  src/pages/request/aids/AidRequest/forms/AmountForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/AmountForm/types.ts
  src/pages/request/aids/AidRequest/forms/BeneficiariesForm/index.tsx
  src/pages/request/aids/AidRequest/forms/BeneficiariesForm/interface.tsx
  src/utils/currency.ts
Labels: minor

#827 feat(aidsMock): add possible regulation validations for aid request
  src/mocks/services/aids/aidsRequest.mocks.ts
  src/model/entity/service.ts
Labels: minor

#829 jlara/1077/create-file-drop-component
  src/design/input/FileDrop/FileDrop.stories.tsx
  src/design/input/FileDrop/index.tsx
  src/design/input/FileDrop/styles.ts
Labels: minor

#830 jlara/1064/aid-regulation-validations-step
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/OutlineCard/styles.ts
  src/components/cards/ValidationCard/ValidationCard.stories.tsx
  src/components/cards/ValidationCard/index.tsx
  src/components/cards/ValidationCard/props.ts
  src/components/modals/general/ValidationDetailsModal/ValidationDetailsModal.stories.tsx
  src/components/modals/general/ValidationDetailsModal/index.tsx
  src/components/modals/general/ValidationDetailsModal/props.ts
  src/components/modals/general/ValidationDetailsModal/styles.ts
  src/design/data/Text/index.tsx
  src/mocks/users/users.mocks.ts
  src/model/entity/service.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/index.tsx
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/types.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/aids/AidRequest/index.tsx
Labels: minor

#831 Crojas/1062/aid details of situation step
  src/design/input/Textarea/index.tsx
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DetailsSituationForm/types.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#832 jlara/1068/create-file-card-component
  src/components/cards/FileCard/FileCard.stories.tsx
  src/components/cards/FileCard/index.tsx
  src/components/cards/FileCard/props.ts
  src/design/input/FileDrop/index.tsx
Labels: minor

#834 jlara/1069/aid-disbursement-step
  src/mocks/users/users.mocks.ts
  src/model/domains/general/updateData/economicActivity/reimbursementTypeDM.ts
  src/model/domains/helper.ts
  src/model/entity/user.ts
  src/pages/admin/home/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/general/UpdateData/forms/BankTransfersForm/types.ts
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/index.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DisbursementForm/types.ts
  src/pages/request/aids/AidRequest/forms/DisbursementForm/utils.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/interface.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
Labels: minor

#835 jlara/1080/config-preview-deploy-data
  src/context/app/index.tsx
  src/mocks/users/users.mocks.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  vite.config.ts
Labels: enhancement

#836 jlara/1081/check-payment-history-dates
  src/pages/admin/payments/PaymentHistory/EmptyRecords/index.tsx
  src/utils/dates.ts
Labels: patch

#841 jlara/1089/fix-product-description-cards
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: enhancement

#840 jlara/1086/not-render-requests-btns-prod
  src/pages/admin/cards/MyCards/config/boxes.tsx
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/cards/MyCards/interface.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/MyCredits/config/boxes.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/credits/MyCredits/interface.tsx
  src/pages/admin/savings/MySavings/config/boxes.tsx
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
Labels: enhancement

#837 Crojas/1024/integrate other values in payments
  src/components/cards/Product/Product.stories.tsx
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/CustomValueModal/utils.ts
  src/mocks/products/cards/creditQuotas.mocks.ts
  src/mocks/products/credits/credits.mocks.ts
  src/mocks/products/investments/investmentsCommitments.mocks.ts
  src/mocks/products/savings/savingsCommitments.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/home/config/products.ts
  src/pages/admin/home/utils.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/types.ts
  src/pages/admin/savings/SavingsCommitments/config/commitments.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/payments/getPaymentOptions/index.ts
  src/services/iclient/payments/getPaymentOptions/mappers.ts
  src/services/iclient/payments/getPaymentOptions/types.ts
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: minor

#842 feat(userCard): create userCard component
  src/components/cards/UserCard/UserCard.stories.tsx
  src/components/cards/UserCard/index.tsx
  src/components/cards/UserCard/props.ts
  src/components/cards/UserCard/styles.ts
Labels: minor

#843 jlara/1095/create-user-switch-route
  src/App.tsx
  src/context/app/index.tsx
  src/pages/admin/switchUser/config/users.ts
  src/pages/admin/switchUser/index.tsx
Labels: minor

#844 feat(featureFlags): add feature flags for payments options
  src/context/app/utils.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/index.tsx
Labels: minor

#845 jlara/1107/connect-app-consulting-users
  src/model/entity/user.ts
  src/pages/admin/switchUser/index.tsx
  src/services/featureFlags/getConsultingUsers/index.ts
  src/services/featureFlags/getConsultingUsers/mappers.ts
Labels: minor

#846 jlara/1101/split-next-and-expired-value
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: enhancement

#847 jlara/1093/add-beneficiaries-contributions
  src/components/layout/PageNotFound/index.tsx
  src/design/layout/Page/index.tsx
  src/pages/admin/home/interface.tsx
  src/services/iclient/cards/getCards/mappers.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
  src/services/iclient/savings/getSavings/utils.ts
  src/utils/texts.ts
Labels: enhancement

#848 crojas/1096/create user switch screen
  src/App.tsx
  src/design/layout/Page/index.tsx
  src/pages/admin/switchUser/index.tsx
  src/pages/admin/switchUser/styles.ts
Labels: minor

#849 jlara/1098/search-user-switch
  src/context/app/index.tsx
  src/context/app/types.ts
  src/pages/admin/switchUser/index.tsx
  src/pages/admin/switchUser/styles.ts
  src/services/featureFlags/getConsultingUsers/mappers.ts
Labels: minor

#850 jlara/1099/save-recent-user-search
  src/context/app/index.tsx
  src/pages/admin/switchUser/index.tsx
  src/pages/admin/switchUser/utils.ts
Labels: enhancement

#851 jlara/1108/nav-switch-user-option
  src/context/app/index.tsx
  src/design/navigation/Header/index.tsx
  src/design/navigation/Menu/Menu.stories.tsx
  src/design/navigation/Menu/MenuSection/MenuSection.stories.tsx
  src/design/navigation/Menu/MenuSection/index.tsx
  src/design/navigation/Menu/MenuSection/types.ts
  src/design/navigation/Menu/index.tsx
  src/pages/admin/switchUser/index.tsx
Labels: enhancement

#853 jlara/1125/add-concepts-values-credits
  src/components/cards/BoxAttribute/ButtonAttribute/index.tsx
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/cards/CurrentConsumption/CurrentConsumption.stories.tsx
  src/components/cards/cards/CurrentConsumption/CurrentConsumptionBox/index.tsx
  src/components/modals/general/NextPaymentModal/index.tsx
  src/config/enviroment.ts
  src/mocks/products/cards/consumptions.mocks.ts
  src/mocks/products/cards/creditQuotas.mocks.ts
  src/pages/admin/cards/Consumption/config/product.ts
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getAmortization/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: major

#854 Develop to main 30/05/2024
  src/components/cards/BoxAttribute/ButtonAttribute/index.tsx
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/cards/CurrentConsumption/CurrentConsumption.stories.tsx
  src/components/cards/cards/CurrentConsumption/CurrentConsumptionBox/index.tsx
  src/components/modals/general/NextPaymentModal/index.tsx
  src/config/enviroment.ts
  src/mocks/products/cards/consumptions.mocks.ts
  src/mocks/products/cards/creditQuotas.mocks.ts
  src/pages/admin/cards/Consumption/config/product.ts
  src/pages/admin/cards/CreditQuota/config/product.ts
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/types.ts
  src/pages/admin/credits/Credit/utils.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getAmortization/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: major
