Repository selsa-inube/app-personas, pull requests merged in 2024-04, with the labels that each got.

#717 sl/848/check-npm-audit
  package-lock.json
Labels: enhancement

#718 sl/814/use-menu-in-user-header
  src/design/data/User/index.tsx
  src/design/layout/Page/index.tsx
  src/design/navigation/Header/index.tsx
  src/design/navigation/Header/styles.ts
  src/design/navigation/Menu/MenuItem/index.tsx
  src/design/navigation/Menu/MenuSection/index.tsx
  src/design/navigation/Menu/styles.ts
Labels: minor

#715 jg/862/Extend-commitments-attributes-to-display-compromisos
  src/pages/admin/savings/SavingsCommitments/config/commitments.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: enhancement

#714 fix: remove section of Solicitar wit all its links from nav and Fulls…
  src/config/nav.tsx
  src/design/navigation/FullscreenNav/FullscreenMenu/index.tsx
Labels: enhancement

#716 jg/857/Page-for-errorElement-paths
  src/App.tsx
  src/components/layout/PageNotFound/index.tsx
Labels: minor

#719 sl/864/fix-correct-cancel-logout
  src/design/layout/Page/styles.ts
  src/design/navigation/Header/index.tsx
  src/design/navigation/Header/styles.ts
  src/design/navigation/Menu/MenuItem/index.tsx
  src/design/navigation/NavLink/index.tsx
Labels: patch

#720 sl/865/deactivate-selects-with-one-product
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
Labels: patch

#712 fix(cards): check first word in cupo movements to decide if we must o…
  src/components/cards/CardMovement/index.tsx
  src/pages/admin/cards/Card/config/product.ts
Labels: enhancement

#723 sl/873/create-screen-pay
  src/pages/admin/payments/Pay/config/assisted.ts
  src/pages/admin/payments/Pay/config/navigation.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/types.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/forms/Verification/config/box.ts
  src/pages/admin/payments/Pay/forms/Verification/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/interface.tsx
  src/pages/admin/payments/Pay/types.ts
  src/routes/payments.tsx
Labels: major

#724 Ap/867/add atribute valor vencido
  src/pages/admin/credits/Credit/config/product.ts
  src/services/iclient/credits/getCredits/mappers.ts
Labels: enhancement

#725 sl/874/create-payment-card
  src/components/cards/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/props.ts
  src/components/cards/PaymentCard/styles.ts
  src/components/modals/cards/InfoModal/index.tsx
  src/components/modals/cards/InfoModal/styles.ts
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/CustomValueModal/styles.ts
  src/design/input/RadioCard/styles.ts
  src/design/input/TextField/styles.ts
  src/pages/admin/cards/Card/config/modals.ts
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/Card/types.ts
Labels: minor

#726 feat: update auth library to v1.0.16
  package-lock.json
  package.json
Labels: dependencies

#727 jg/826/Integrate-consumption-list-from-creditQuotaDetail-endpoint
  src/components/cards/CurrentConsumption/CurrentConsumptionBox/index.tsx
  src/components/cards/CurrentConsumption/index.tsx
  src/context/cards/index.tsx
  src/context/cards/types.ts
  src/mocks/products/cards/cards.mocks.ts
  src/mocks/products/cards/creditQuotas.mocks.ts
  src/model/entity/product.ts
  src/pages/admin/cards/Consumption/config/product.ts
  src/pages/admin/cards/Consumption/index.tsx
  src/pages/admin/cards/Consumption/interface.tsx
  src/pages/admin/cards/Consumption/utils.ts
  src/pages/admin/cards/CreditQuota/index.tsx
  src/pages/admin/cards/CreditQuota/interface.tsx
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/index.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
Labels: minor

#728 sl/881/create-payment-help-modal
  src/components/modals/payments/PaymentHelpModal/index.tsx
  src/components/modals/payments/PaymentHelpModal/styles.ts
Labels: minor

#729 sl/882/create-payment-filter-modal
  src/components/modals/payments/PaymentFilterModal/index.tsx
  src/components/modals/payments/PaymentFilterModal/styles.ts
Labels: minor

#730 sl/883/extend-tag-include-removable
  src/design/data/Tag/Tag.stories.tsx
  src/design/data/Tag/index.tsx
  src/design/data/Tag/props.ts
  src/design/data/Tag/styles.ts
Labels: minor

#731 sl/884/create-mock-payments
  src/components/cards/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/props.ts
  src/components/modals/general/updateData/RelationshipWithDirectorsModal/index.tsx
  src/mocks/payments/payments.mocks.ts
  src/mocks/users/directors/directors.mocks.ts
  src/model/entity/payment.ts
  src/model/entity/user.ts
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/index.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
Labels: minor

#732 sl/885/content-obligations-step
  src/components/cards/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/PaymentCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/PaymentFilterModal/index.tsx
  src/components/modals/payments/PaymentHelpModal/index.tsx
  src/mocks/payments/payments.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/filters.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/types.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/interface.tsx
  src/utils/currency.ts
  src/utils/forms/forms.tsx
Labels: minor

#733 sl/887/connect-filter-modal
  src/components/modals/payments/CustomValueModal/styles.ts
  src/components/modals/payments/PaymentFilterModal/index.tsx
  src/components/modals/payments/PaymentFilterModal/styles.ts
  src/components/modals/payments/PaymentHelpModal/styles.ts
  src/mocks/payments/payments.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/filters.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
Labels: minor

#734 sl/890/connect-help-modal-payments
  src/components/cards/PaymentCard/index.tsx
  src/components/modals/payments/PaymentFilterModal/index.tsx
  src/components/modals/payments/PaymentHelpModal/index.tsx
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
Labels: minor

#735 sl/891/add-obligations-verification
  src/components/cards/PaymentCard/index.tsx
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#737 sl/893/create-payment-method-step
  src/components/cards/PaymentCard/index.tsx
  src/components/modals/general/updateData/AssetModal/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/design/input/Fieldset/index.tsx
  src/design/input/Fieldset/styles.ts
  src/design/input/TextField/interface.tsx
  src/mocks/payments/moneySources.mocks.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/config/payment.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
Labels: minor

#738 sl/903/fix-payment-method-bugs
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
Labels: patch

#739 sl/901/connect-with-featured-flags
  package-lock.json
  package.json
  src/App.tsx
  src/config/enviroment.ts
  src/config/header.tsx
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/context/cards/index.tsx
  src/context/credits/index.tsx
  src/context/savings/index.tsx
  src/design/layout/Page/index.tsx
  src/model/entity/featuredFlag.ts
  src/pages/admin/home/index.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/config/navigation.ts
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/services/database/supabase/config.ts
  src/services/featuredFlags/db.sql
  src/services/featuredFlags/getFeaturedFlag/index.ts
  src/services/featuredFlags/getFeaturedFlag/mappers.ts
  src/services/featuredFlags/getFeaturedFlags/index.ts
  src/services/featuredFlags/getFeaturedFlags/mappers.ts
Labels: minor

#740 sl/905/adjust-structure-consult-flag
  src/config/header.tsx
  src/context/app/index.tsx
  src/context/app/types.ts
  src/context/app/utils.ts
  src/design/layout/Page/index.tsx
  src/model/entity/featuredFlag.ts
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/services/featuredFlags/getFeaturedFlag/index.ts
  src/services/featuredFlags/getFeaturedFlag/mappers.ts
  src/services/featuredFlags/getFeaturedFlags/index.ts
Labels: enhancement

#741 sl/906/fix-product-cards-loading
  src/pages/admin/home/index.tsx
Labels: patch

#742 sl/907/adjusts-in-payments
  src/components/modals/payments/CustomValueModal/index.tsx
  src/design/input/Select/interface.tsx
  src/design/input/TextField/interface.tsx
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/types.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
Labels: patch

#743 sl/917/select-single-account
  package-lock.json
  package.json
  src/main.tsx
  src/mocks/payments/moneySources.mocks.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
Labels: minor

#745 refactor(myCredits): fix attributes in myCredits
  src/pages/admin/credits/MyCredits/interface.tsx
Labels: patch

#744 Cr/914/add trash icon in pay cards
  src/components/cards/PaymentCard/index.tsx
Labels: enhancement

#747 sl/941/remove-proximos-vencer-option
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/filters.ts
Labels: enhancement

#748 feat(card): use skeletons when the user access to card details
  src/components/cards/Box/Box.stories.tsx
  src/components/cards/Box/index.tsx
  src/components/cards/Box/props.ts
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/interface.tsx
Labels: enhancement

#749 sl/953/fix-values-commitments
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/savings/getSavings/mappers.ts
Labels: patch

#750 sl/942/fix-payment-apply-decision
  src/components/cards/PaymentCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
Labels: patch

#752 feat(paymentCard): adjust wrap in payments cards
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/styles.ts
Labels: patch

#753 sl/958/use-interest-payment-cdat
  src/mocks/products/savings/utils.mocks.ts
  src/services/iclient/savings/getSavings/utils.ts
Labels: patch

#755 sl/959/update-design-payment-method
  src/components/cards/PaymentMethodCard/index.tsx
  src/components/cards/PaymentMethodCard/styles.ts
  src/design/input/TextField/interface.tsx
  src/mocks/payments/moneySources.mocks.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#757 sl/960/create-json-payment-request
  src/config/enviroment.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/utils.ts
  src/services/iclient/payments/createPaymentRequest/index.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: minor

#758 sl/962/use-real-savings-payment-method
  src/mocks/products/credits/credits.mocks.ts
  src/mocks/products/savings/savings.mocks.ts
  src/mocks/products/savings/savingsCommitments.mocks.ts
  src/mocks/users/users.mocks.ts
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/utils.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/credits/getCredits/index.ts
  src/services/iclient/savings/getCommitments/index.ts
  src/services/iclient/savings/getSavings/index.ts
Labels: minor

#756 sl/953/adjust-commitment-card
  src/components/cards/CommitmentCard/CommitmentCard.stories.tsx
  src/components/cards/CommitmentCard/index.tsx
  src/components/cards/CommitmentCard/props.ts
  src/components/cards/CommitmentCard/styles.ts
  src/pages/admin/home/ProductsCommitments/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/home/interface.tsx
  src/pages/admin/home/utils.ts
  src/pages/admin/savings/MySavings/index.tsx
  src/pages/admin/savings/MySavings/interface.tsx
  src/pages/admin/savings/SavingsCommitments/config/commitments.ts
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: enhancement

#760 sl/966/add-flags-request-buttons
  src/context/app/utils.ts
  src/pages/admin/home/config/boxes.tsx
  src/pages/admin/home/interface.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateDataUnassisted/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditRequest/index.tsx
  src/pages/request/savings/CdatRequest/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/index.tsx
  src/pages/request/savings/SavingRequest/index.tsx
Labels: enhancement

#759 sl/964/align-label-and-value-payments
  src/components/cards/PaymentCard/index.tsx
Labels: enhancement

#762 sl/965/resumen-should-always-visible
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/interface.tsx
  src/pages/admin/payments/Pay/styles.ts
Labels: enhancement

#763 sl/963/total-payment-always-visible
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
  src/pages/admin/payments/Pay/interface.tsx
  src/pages/admin/payments/Pay/styles.ts
Labels: enhancement

#761 Cr/918/add modal for total pay value is formed
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentInformationCard/PaymentInformationCard.stories.tsx
  src/components/cards/PaymentInformationCard/index.tsx
  src/components/cards/PaymentInformationCard/props.ts
  src/components/cards/PaymentInformationCard/styles.ts
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/PaymentTotalModal/index.tsx
  src/components/modals/payments/PaymentTotalModal/styles.ts
  src/design/layout/Blanket/index.tsx
  src/design/layout/Blanket/styles.ts
  src/mocks/payments/payments.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
Labels: minor

#764 sl/975/redirect-not-found-payments
  src/routes/payments.tsx
Labels: enhancement

#766 sl/977/adjust-total-pay-fixed
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/styles.ts
Labels: patch

#765 sl/967/use-new-flags-structure
  src/services/featuredFlags/getFeaturedFlag/index.ts
  src/services/featuredFlags/getFeaturedFlag/mappers.ts
  src/services/featuredFlags/getFeaturedFlags/index.ts
  src/services/featuredFlags/getFeaturedFlags/mappers.ts
Labels: minor

#768 sl/982/fix-multiple-fetch-credits
  src/pages/admin/cards/MyCards/index.tsx
  src/pages/admin/credits/MyCredits/index.tsx
  src/pages/admin/home/index.tsx
  src/pages/admin/savings/MySavings/index.tsx
Labels: patch

#767 sl/981/use-obligations-in-payments
  src/components/cards/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/styles.ts
  src/components/cards/PaymentMethodCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/components/modals/payments/PaymentHelpModal/index.tsx
  src/components/modals/saving/SavingCommitmentsModal/index.tsx
  src/mocks/products/credits/credits.mocks.ts
  src/mocks/products/investments/investmentsCommitments.mocks.ts
  src/mocks/products/savings/savingsCommitments.mocks.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/home/utils.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/filters.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/types.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/config/payment.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/types.ts
  src/pages/admin/savings/SavingsCommitments/config/commitments.ts
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/savings/SavingsCommitments/utils.ts
  src/services/config/supabase/config.ts
  src/services/featuredFlags/getFeaturedFlags/index.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: major

#770 sl/979/correct-label-custom-value
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/styles.ts
  src/components/modals/payments/CustomValueModal/index.tsx
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/pages/admin/payments/Pay/index.tsx
Labels: patch

#771 sl/984/changes-payment-request
  src/model/entity/payment.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: enhancement

#769 Cr/949/mock historico de pagos page
  src/components/cards/PaymentHistoryCard/PaymentHistoryCard.stories.tsx
  src/components/cards/PaymentHistoryCard/index.tsx
  src/components/cards/PaymentHistoryCard/props.ts
  src/components/cards/PaymentHistoryCard/styles.ts
  src/components/modals/payments/PaymentHistoryModal/index.tsx
  src/components/modals/payments/PaymentHistoryModal/styles.ts
  src/mocks/payments/paymentHistory.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/PaymentHistory/config/navigation.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/routes/payments.tsx
Labels: minor

#774 sl/985/fix-apply-filters
  src/components/cards/PaymentMethodCard/index.tsx
  src/mocks/payments/moneySources.mocks.ts
  src/mocks/users/users.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/utils.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: patch

#773 fix(totalToPay): adjust media queries of total to pay component
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/interface.tsx
Labels: patch

#776 sl/987/get-accounts-payments
  src/components/cards/PaymentMethodCard/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
Labels: patch

#777 sl/988/adjust-saving-accounts-payment-method
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
Labels: patch

#778 sl/989/fix-error-pay-with-account
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: patch

#779 sl/990/fix-other-value-selection
  src/components/modals/payments/CustomValueModal/index.tsx
Labels: patch

#780 fix(pageNotFound): adjust page not found
  src/App.tsx
  src/components/layout/PageNotFound/index.tsx
  src/components/layout/PageNotFound/styles.ts
Labels: minor

#781 sl/992/fetch-payments-history
  src/components/cards/PaymentHistoryCard/PaymentHistoryCard.stories.tsx
  src/components/cards/PaymentHistoryCard/index.tsx
  src/components/cards/PaymentHistoryCard/props.ts
  src/components/modals/payments/PaymentHistoryModal/index.tsx
  src/mocks/payments/paymentHistory.mocks.ts
  src/mocks/payments/utils.mocks.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
Labels: minor

#782 sl/997/much-cards-possible-payments
  src/components/cards/PaymentCard/index.tsx
  src/components/cards/PaymentCard/styles.ts
  src/components/modals/payments/CustomValueModal/index.tsx
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/cards.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: minor

#783 sl/995/remove-filters-fieldset
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
Labels: enhancement

#786 sl/1000/refactor-payment-method-card
  src/components/cards/PaymentMethodCard/index.tsx
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/interface.tsx
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/styles.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/types.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#784 Cr/976/refactor attributes in commitments cards
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: enhancement

#787 sl/1001/loading-sending-payment
  src/design/feedback/Assisted/index.tsx
  src/design/feedback/Assisted/interface.tsx
  src/pages/admin/payments/Pay/LoadingPayment/index.tsx
  src/pages/admin/payments/Pay/LoadingPayment/styles.ts
  src/pages/admin/payments/Pay/interface.tsx
Labels: minor

#789 Cr/999/refactor totalizer component
  src/components/layout/Totalizer/index.tsx
  src/components/layout/Totalizer/styles.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/styles.ts
  src/pages/admin/payments/Pay/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#788 sl/1002/fix-payment-history-values
  src/components/cards/PaymentHistoryCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/PaymentMethodForm/index.tsx
  src/pages/admin/payments/Pay/types.ts
  src/pages/admin/payments/PaymentHistory/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/services/iclient/payments/getPaymentHistory/index.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
Labels: patch

#790 sl/1003/adjust-cards-values
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/utils.ts
  src/pages/admin/cards/CreditQuota/index.tsx
  src/pages/admin/cards/CreditQuota/utils.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
Labels: enhancement
