Repository selsa-inube/app-personas, pull requests merged in 2024-07, with the labels that each got.

#899 jlara/1206/use-outline-simulate-credit
  src/components/modals/credit/CreditDisbursementModal/index.tsx
  src/components/modals/credit/CreditDisbursementModal/styles.ts
  src/mocks/products/credits/request.mocks.ts
  src/model/domains/general/peridiocityDM.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
Labels: minor

#898 Crojas/1192/change table in my credits for record cards
  src/components/cards/RecordCard/RecordCard.stories.tsx
  src/components/cards/RecordCard/index.tsx
  src/components/cards/RecordCard/props.ts
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/credits/Credit/config/attributeRecord.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/styles.ts
  src/pages/admin/credits/CreditMovements/config/attributeRecord.ts
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/CreditMovements/styles.ts
  src/pages/admin/credits/MyCredits/ViewMovement/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
Labels: minor

#900 Crojas/1161/create json with fondecom tokens
  src/components/cards/RecordCard/RecordCard.stories.tsx
  src/components/cards/RecordCard/index.tsx
  src/components/cards/RecordCard/props.ts
  src/components/modals/credit/CreditDisbursementModal/index.tsx
  src/components/modals/credit/CreditDisbursementModal/styles.ts
  src/components/modals/credit/CreditMovementModal/index.tsx
  src/mocks/design/themes/fondecom/fondecom.json
  src/mocks/design/themes/fondecom/index.ts
  src/mocks/products/credits/request.mocks.ts
  src/model/domains/general/peridiocityDM.ts
  src/pages/admin/cards/Card/interface.tsx
  src/pages/admin/cards/CardMovements/interface.tsx
  src/pages/admin/credits/Credit/config/attributeRecord.ts
  src/pages/admin/credits/Credit/index.tsx
  src/pages/admin/credits/Credit/interface.tsx
  src/pages/admin/credits/Credit/styles.ts
  src/pages/admin/credits/CreditMovements/config/attributeRecord.ts
  src/pages/admin/credits/CreditMovements/index.tsx
  src/pages/admin/credits/CreditMovements/interface.tsx
  src/pages/admin/credits/CreditMovements/styles.ts
  src/pages/admin/credits/MyCredits/ViewMovement/index.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/savings/SavingsAccount/interface.tsx
  src/pages/admin/savings/SavingsAccountMovements/interface.tsx
  src/pages/admin/savings/SavingsCommitments/interface.tsx
  src/pages/admin/switchUser/config/users.ts
  src/pages/admin/transfers/TransferHistory/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
Labels: major

#901 Inubekit
  src/mocks/design/themes/fondecom/fondecom.json
  src/mocks/design/themes/fondecom/index.ts
Labels: major

#902 jlara/1219/credit-documentary-requirements
  package-lock.json
  package.json
  src/components/cards/FileCard/index.tsx
  src/components/cards/InfoCard/InfoCard.stories.tsx
  src/components/cards/InfoCard/index.tsx
  src/components/cards/InfoCard/props.ts
  src/components/cards/InfoCard/styles.ts
  src/components/cards/InfoCard/types.ts
  src/design/input/Button/styles.ts
  src/design/tokens/color/palette.ts
  src/mocks/design/themes/fondecom/color/palette.ts
  src/mocks/design/themes/fondecom/fondecom.json
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
Labels: minor

#903 jlara/1209/credit-validations-step
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/ValidationCard/index.tsx
  src/components/modals/general/ValidationDetailsModal/index.tsx
  src/mocks/products/credits/request.mocks.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PreliquidationForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
Labels: minor

#907 jlara/1235/disable-some-filter-payments
  src/pages/admin/payments/Pay/forms/ObligationsForm/config/filters.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
Labels: enhancement

#906 jlara/1213/mock-my-requests-data
  src/mocks/products/credits/requests.mocks.ts
  src/model/domains/credits/requestStatusDM.ts
  src/model/entity/request.ts
Labels: minor

#910 jlara/1226/obfuscate-card-number
  src/model/entity/product.ts
  src/pages/admin/cards/Card/config/product.ts
  src/pages/admin/cards/Card/index.tsx
  src/pages/admin/cards/Card/interface.tsx
  src/services/iclient/cards/getCards/mappers.ts
  src/utils/texts.ts
Labels: minor

#911 jlara/1227/rename-first-step-credit
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
Labels: enhancement

#913 jlara/1228/modal-leave-payment
  src/components/modals/general/DecisionModal/index.tsx
  src/pages/admin/payments/Pay/index.tsx
  src/pages/admin/payments/Pay/interface.tsx
  src/pages/admin/requests/MyRequests/interface.tsx
Labels: enhancement

#919 sl/1022/use-obligations-payments
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/modals/payments/CustomValueModal/index.tsx
  src/mocks/payments/payments.mocks.ts
  src/model/domains/payments/otherValueAvailableDM.ts
  src/model/entity/payment.ts
  src/pages/admin/payments/Pay/config/mappers.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/types.ts
  src/pages/admin/payments/Pay/index.tsx
  src/services/iclient/payments/getCreditPayments/index.ts
  src/services/iclient/payments/getCreditPayments/mappers.ts
Labels: minor

#921 jlara/1238/integrate-endpoint-destinations
  src/pages/request/credits/CreditDestinationRequest/config/mappers.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/services/iclient/credits/getDestinations/index.ts
  src/services/iclient/credits/getDestinations/mappers.ts
Labels: minor

#920 feat(spinner): replace spinner component from inubekit
  package-lock.json
  package.json
  src/components/cards/ValidationCard/index.tsx
  src/components/modals/general/LoadingModal/index.tsx
  src/design/feedback/Spinner/Spinner.stories.tsx
  src/design/feedback/Spinner/index.tsx
  src/design/feedback/Spinner/props.ts
  src/design/feedback/Spinner/styles.ts
  src/design/feedback/Spinner/types.ts
  src/design/input/Button/index.tsx
  src/mocks/design/themes/fondecom/fondecom.ts
Labels: minor

#923 Crojas/1182/replace skeleton component from inubekit
  package-lock.json
  package.json
  src/components/cards/Box/index.tsx
  src/components/cards/Product/index.tsx
  src/components/cards/RecordCard/index.tsx
  src/design/data/Table/interface.tsx
  src/mocks/design/themes/fondecom/fondecom.ts
Labels: minor

#926 jlara/1242/download-btn-amortization
  src/pages/admin/credits/CreditAmortization/index.tsx
Labels: enhancement

#928 jlara/1243/mock-downloadable-plan-pagos
  package-lock.json
  src/components/cards/Box/index.tsx
  src/config/header.tsx
  src/pages/admin/credits/CreditAmortization/AmortizationDocument/index.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
Labels: minor

#930 jlara/1244/download-amortization
  src/mocks/products/credits/credits.mocks.ts
  src/model/domains/general/periodicityDM.ts
  src/pages/admin/credits/Credit/config/product.ts
  src/pages/admin/credits/CreditAmortization/AmortizationDocument/index.tsx
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/styles.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/interface.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/services/iclient/credits/getCredits/mappers.ts
  src/utils/print.ts
Labels: minor

#931 jlara/1245/change-group-names-validations
  src/components/cards/ValidationCard/index.tsx
  src/model/entity/service.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
Labels: enhancement

#933 jlara/1248/pdf-visualizer-amortization
  package-lock.json
  package.json
  src/components/modals/general/ExportModal/index.tsx
  src/components/modals/general/ExportModal/styles.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/styles.ts
  src/pages/admin/credits/CreditAmortization/utilRenders.tsx
  src/pages/admin/credits/CreditAmortization/utils.ts
  src/utils/dates.ts
  src/utils/print.ts
Labels: minor
