Repository selsa-inube/app-personas, pull requests merged in 2024-08, with the labels that each got.

#936 jlara/1256/integrate-requirements-endpoint
  src/components/cards/OutlineCard/styles.ts
  src/components/cards/ValidationCard/index.tsx
  src/components/modals/general/AttachDocumentModal/index.tsx
  src/components/modals/general/AttachDocumentModal/styles.ts
  src/design/input/Button/index.tsx
  src/design/input/FileDrop/index.tsx
  src/design/input/FileDrop/styles.ts
  src/model/entity/request.ts
  src/model/entity/service.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getRequirements/index.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/utils/texts.ts
Labels: minor

#938 Develop to main
  src/components/layout/PageNotFound/index.tsx
  src/config/nav.tsx
  src/design/layout/Page/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/shared/forms/ContactChannelsForm/mappers.ts
Labels: minor

#942 jlara/1259/move-data-policy-credit
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/shared/forms/ContactChannelsForm/index.tsx
  src/shared/forms/ContactChannelsForm/interface.tsx
  src/shared/forms/ContactChannelsForm/mappers.ts
  src/shared/forms/ContactChannelsForm/styles.ts
  src/shared/forms/ContactChannelsForm/types.ts
Labels: minor

#943 jlara/1250/download-full-amortization
  src/pages/admin/credits/CreditAmortization/utilRenders.tsx
Labels: minor

#944 jlara/1253/adjust-export-modal
  src/components/modals/general/ExportModal/index.tsx
  src/components/modals/general/ExportModal/styles.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
Labels: enhancement

#945 Develop to main
  src/components/modals/general/ExportModal/index.tsx
  src/components/modals/general/ExportModal/styles.ts
  src/pages/admin/credits/CreditAmortization/index.tsx
  src/pages/admin/credits/CreditAmortization/utilRenders.tsx
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/styles.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/Summary/SummaryBoxes/index.tsx
  src/shared/forms/ContactChannelsForm/index.tsx
  src/shared/forms/ContactChannelsForm/interface.tsx
  src/shared/forms/ContactChannelsForm/mappers.ts
  src/shared/forms/ContactChannelsForm/styles.ts
  src/shared/forms/ContactChannelsForm/types.ts
Labels: minor

#934 feat(label): replace label component from inubekit
  package-lock.json
  package.json
  src/design/input/DateField/interface.tsx
  src/design/input/Label/Label.stories.tsx
  src/design/input/Label/index.tsx
  src/design/input/Label/props.ts
  src/design/input/Label/styles.ts
  src/design/input/Select/interface.tsx
  src/design/input/Switch/index.tsx
  src/design/input/TextField/interface.tsx
  src/design/input/Textarea/index.tsx
  src/mocks/design/themes/fondecom/fondecom.ts
  src/mocks/design/themes/fondecom/index.ts
Labels: minor

#946 Crojas/1269/adjust condiciones de credito step
  src/design/feedback/SectionMessage/index.tsx
  src/model/entity/request.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getCalculatedConditionsForProduct/index.ts
  src/services/iclient/credits/getCalculatedConditionsForProduct/mappers.ts
  src/services/iclient/credits/getCalculatedConditionsForProduct/types.ts
  src/services/iclient/credits/getPaymentMethods/index.ts
  src/services/iclient/credits/getPaymentMethodsForProduct/index.ts
  src/services/iclient/credits/getPaymentMethodsForProduct/mappers.ts
  src/services/iclient/credits/getPeriodicity/index.ts
  src/services/iclient/credits/getPeriodicityForProduct/index.ts
  src/services/iclient/credits/getPeriodicityForProduct/mappers.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/credits/simulateCreditConditions/index.ts
  src/services/iclient/credits/simulateCreditConditions/mappers.ts
  src/services/iclient/credits/simulateCreditConditions/types.ts
Labels: major

#948 jlara/1272/two-options-disbursement
  src/mocks/domains/disbursementType.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
Labels: minor

#949 jlara/1265/adjusts-credit-conditions
  src/model/entity/periodicity.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getPeriodicitiesForProduct/index.ts
  src/services/iclient/credits/getPeriodicitiesForProduct/mappers.ts
Labels: minor

#950 jlara/1273/adjusts-props-requests
  src/services/iclient/cards/getCards/index.ts
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getCredits/index.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/payments/getCardPayments/index.ts
  src/services/iclient/payments/getCardPayments/mappers.ts
  src/services/iclient/payments/getCommitmentPayments/mappers.ts
  src/services/iclient/payments/getCreditPayments/index.ts
  src/services/iclient/payments/getCreditPayments/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
Labels: major

#952 feat(creditRequest): include forma de pago step
  src/mocks/domains/accountSelectionType.ts
  src/mocks/domains/domainService.mocks.ts
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
Labels: minor

#953 Develop to main
  src/mocks/domains/accountSelectionType.ts
  src/mocks/domains/domainService.mocks.ts
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/PaymentMethodForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/config/termsAndConditions.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/credits/simulateCreditConditions/mappers.ts
Labels: major

#954 fix(creditRequest): filter destinations
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/services/iclient/credits/getDestinations/mappers.ts
Labels: minor

#955 jlara/1280/rem-quick-access-credit-request
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
Labels: patch

#956 jlara/1279/add-disbursement-method
  src/mocks/domains/disbursementType.ts
Labels: minor

#957 jlara/1278/refactor-validation-card
  src/config/enviroment.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
Labels: enhancement

#960 jlara/1281/active-update-data
  src/components/cards/BoxAttribute/index.tsx
  src/components/modals/general/updateData/ReferenceModal/index.tsx
  src/config/header.tsx
  src/design/feedback/Assisted/interface.tsx
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BeneficiariesForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/initialValues.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/utils.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/validations/validationRules.ts
Labels: minor

#961 Develop to main
  src/components/cards/BoxAttribute/index.tsx
  src/components/cards/credits/DestinationCard/index.tsx
  src/components/modals/general/updateData/ReferenceModal/index.tsx
  src/config/enviroment.ts
  src/config/header.tsx
  src/design/feedback/Assisted/interface.tsx
  src/mocks/domains/disbursementType.ts
  src/pages/general/UpdateData/config/mappers.ts
  src/pages/general/UpdateData/forms/BeneficiariesForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/initialValues.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/types.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/Verification/VerificationFieldsets/index.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/utils.ts
  src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DestinationForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
  src/pages/request/savings/CdatRequest/forms/ConditionsForm/utils.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/GoalForm/index.tsx
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
  src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
  src/utils/forms/forms.tsx
  src/validations/validationRules.ts
Labels: minor

#963 Develop to main
  src/pages/general/UpdateData/interface.tsx
Labels: minor

#964 jlara/1276/temp-payment-method-credit
  src/model/entity/user.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getProducts/index.ts
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/credits/getRequirements/types.ts
  src/services/iclient/customers/getCustomer/index.ts
  src/services/iclient/customers/getCustomer/mappers.ts
Labels: minor

#965 jlara/1286/refactor-quotas-field
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/VerificationBoxes/index.tsx
Labels: enhancement

#966 jlara/1287/nuip-document-type
  src/model/domains/general/updateData/personalInformation/identificationTypeDM.ts
Labels: enhancement

#968 jlara/1290/render-correct-beneficiaries
  src/pages/general/UpdateData/forms/BeneficiariesForm/index.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/interface.tsx
  src/pages/general/UpdateData/forms/BeneficiariesForm/types.ts
  src/pages/general/UpdateData/forms/Verification/VerificationBoxes/index.tsx
  src/pages/general/UpdateData/index.tsx
  src/pages/general/UpdateData/utils.ts
  src/pages/general/UpdateDataUnassisted/index.tsx
Labels: enhancement

#972 jlara/1303/credit-modal-leaving
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
Labels: enhancement

#973 jlara/1300/fix-layout-update-data
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
Labels: patch

#974 jlara/1308/two-columns-amount
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/AmountForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/AmountForm/types.ts
  src/pages/request/aids/AidRequest/forms/Verification/VerificationBoxes/index.tsx
Labels: enhancement

#975 jlara/1309/adjust-validations-separate
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/index.tsx
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/index.tsx
Labels: enhancement

#977 feat(link): replace link component from inubekit
  package-lock.json
  package.json
  src/mocks/design/themes/fondecom/fondecom.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/styles.ts
Labels: minor

#980 fix(aids): use label numero de cuenta in disbursement
  src/pages/request/aids/AidRequest/forms/DisbursementForm/interface.tsx
Labels: enhancement

#978 jlara/1292/datefield-add-debt
  src/components/modals/general/updateData/DebtModal/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/EditDebt/index.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/EditDebt/interface.tsx
  src/pages/general/UpdateData/forms/PersonalDebtsForm/interface.tsx
  src/validations/regularExpressions.ts
  src/validations/validationRules.ts
Labels: enhancement

#979 jlara/1298/disable-contract-undefined
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
Labels: enhancement

#981 jlara/1301/remove-quick-access-saving
  src/pages/request/savings/ProgrammedSavingFixedRequest/interface.tsx
Labels: enhancement

#983 jlara/1305/integrate-terms-endpoint
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/TermsAndConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/services/iclient/credits/getTermsConditions/index.ts
  src/services/iclient/credits/getTermsConditions/mappers.ts
  src/services/iclient/credits/simulateCreditConditions/mappers.ts
Labels: minor

#969 feat(tag): replace tag component from inubekit
  package-lock.json
  package.json
  src/components/cards/Box/Box.stories.tsx
  src/components/cards/Box/index.tsx
  src/components/cards/CommitmentCard/index.tsx
  src/components/cards/Product/index.tsx
  src/components/cards/RecordCard/RecordCard.stories.tsx
  src/components/cards/RecordCard/index.tsx
  src/components/cards/ValidationCard/index.tsx
  src/components/cards/payments/PaymentCard/PaymentCard.stories.tsx
  src/components/cards/payments/PaymentCard/index.tsx
  src/components/cards/payments/PaymentMethodCard/index.tsx
  src/components/modals/payments/PaymentHistoryModal/index.tsx
  src/design/data/Tag/Tag.stories.tsx
  src/design/data/Tag/index.tsx
  src/design/data/Tag/props.ts
  src/design/data/Tag/styles.ts
  src/design/data/Tag/types.ts
  src/mocks/design/themes/fondecom/fondecom.ts
  src/mocks/payments/paymentHistory.mocks.ts
  src/mocks/payments/payments.mocks.ts
  src/mocks/products/cards/cards.mocks.ts
  src/mocks/products/credits/requests.mocks.ts
  src/mocks/transfers/transferHistory.mocks.ts
  src/model/entity/payment.ts
  src/model/entity/product.ts
  src/model/entity/request.ts
  src/model/entity/transfer.ts
  src/pages/admin/payments/Pay/forms/ObligationsForm/index.tsx
  src/pages/admin/payments/Pay/forms/ObligationsForm/interface.tsx
  src/pages/admin/payments/PaymentHistory/interface.tsx
  src/pages/admin/transfers/TransferHistory/interface.tsx
  src/services/iclient/cards/getCreditQuotaDetail/mappers.ts
  src/services/iclient/cards/getCreditQuotas/mappers.ts
  src/services/iclient/credits/getCredits/mappers.ts
  src/services/iclient/payments/getCardPayments/mappers.ts
  src/services/iclient/payments/getCommitmentPayments/mappers.ts
  src/services/iclient/payments/getCreditPayments/mappers.ts
  src/services/iclient/payments/getPaymentHistory/mappers.ts
  src/services/iclient/requests/getRequests/mappers.ts
  src/services/iclient/savings/getCommitments/mappers.ts
  src/services/iclient/transfers/getTransferHistory/mappers.ts
Labels: minor

#984 jlara/1299/rem-success-messages-ud
  src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
  src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/EconomicActivityForm/interface.tsx
  src/pages/general/UpdateData/forms/ExpensesForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/PersonalDataForm/interface.tsx
  src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
  src/pages/general/UpdateData/forms/IncomesForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalInformationForm/interface.tsx
  src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
  src/pages/general/UpdateData/forms/RelationshipWithDirectorsForm/interface.tsx
  src/pages/general/UpdateData/forms/SocioeconomicInformationForm/interface.tsx
Labels: minor

#986 jlara/1315/disbursement-registered-account
  src/mocks/domains/disbursementType.ts
  src/model/domains/general/accountTypeDM.ts
  src/model/domains/general/bankDM.ts
  src/model/domains/general/disbursementTypeDM.ts
  src/pages/request/credits/CreditDestinationRequest/config/assisted.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/CreditConditionsForm/utils.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/config/form.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/index.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DisbursementForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/forms/Verification/config/box.ts
  src/pages/request/credits/CreditDestinationRequest/index.tsx
  src/pages/request/credits/CreditDestinationRequest/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/types.ts
  src/pages/request/credits/CreditDestinationRequest/utils.ts
  src/utils/forms/forms.tsx
Labels: minor

#990 jlara/1334/adjust-props-payment
  src/services/iclient/credits/getRequirements/mappers.ts
  src/services/iclient/payments/createPaymentRequest/mappers.ts
Labels: patch

#989 jlara/1332/screen-no-documents
  src/components/cards/InfoCard/index.tsx
  src/components/cards/InfoCard/styles.ts
  src/components/modals/general/AttachDocumentModal/index.tsx
  src/pages/request/aids/AidRequest/config/mappers.ts
  src/pages/request/aids/AidRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/aids/AidRequest/forms/DocumentaryRequirementsForm/types.ts
  src/pages/request/credits/CreditDestinationRequest/config/initialValues.ts
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/DocumentaryRequirementsForm/types.ts
Labels: minor

#991 jlara/1331/screen-no-validations
  src/pages/request/aids/AidRequest/forms/RegulationValidationsForm/interface.tsx
  src/pages/request/credits/CreditDestinationRequest/forms/SystemValidationsForm/interface.tsx
  src/services/iclient/credits/simulateCreditConditions/index.ts
Labels: enhancement
